import Concrete.Codegen.Emit

namespace Concrete

/-- Emit LLVM IR for all built-in standard library functions. -/
def genBuiltinFunctions (s : CodegenState) : CodegenState :=
  -- Built-in string functions
  let s := s.emit "define i64 @string_length(ptr %s) {"
  let s := s.emit "  %len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len = load i64, ptr %len_ptr"
  let s := s.emit "  ret i64 %len"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "define void @drop_string(ptr %s) {"
  let s := s.emit "  %data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data = load ptr, ptr %data_ptr"
  let s := s.emit "  call void @free(ptr %data)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "define void @print_string(ptr %s) {"
  let s := s.emit "  %data_ptr.ps = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data.ps = load ptr, ptr %data_ptr.ps"
  let s := s.emit "  %len_ptr.ps = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len.ps = load i64, ptr %len_ptr.ps"
  let s := s.emit "  %unused = call i64 @write(i32 1, ptr %data.ps, i64 %len.ps)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_concat: takes two Strings by value, returns a new String
  let s := s.emit "define %struct.String @string_concat(ptr %a, ptr %b) {"
  let s := s.emit "  %a_data_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 0"
  let s := s.emit "  %a_data = load ptr, ptr %a_data_ptr"
  let s := s.emit "  %a_len_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 1"
  let s := s.emit "  %a_len = load i64, ptr %a_len_ptr"
  let s := s.emit "  %b_data_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 0"
  let s := s.emit "  %b_data = load ptr, ptr %b_data_ptr"
  let s := s.emit "  %b_len_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 1"
  let s := s.emit "  %b_len = load i64, ptr %b_len_ptr"
  let s := s.emit "  %total_len = add i64 %a_len, %b_len"
  let s := s.emit "  %buf = call ptr @malloc(i64 %total_len)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)"
  let s := s.emit "  %dst = getelementptr i8, ptr %buf, i64 %a_len"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)"
  let s := s.emit "  ; Free the input strings"
  let s := s.emit "  call void @free(ptr %a_data)"
  let s := s.emit "  call void @free(ptr %b_data)"
  let s := s.emit "  %sc_alloca = alloca %struct.String"
  let s := s.emit "  %sc_data_ptr = getelementptr inbounds %struct.String, ptr %sc_alloca, i32 0, i32 0"
  let s := s.emit "  store ptr %buf, ptr %sc_data_ptr"
  let s := s.emit "  %sc_len_ptr = getelementptr inbounds %struct.String, ptr %sc_alloca, i32 0, i32 1"
  let s := s.emit "  store i64 %total_len, ptr %sc_len_ptr"
  let s := s.emit "  %sc_result = load %struct.String, ptr %sc_alloca"
  let s := s.emit "  ret %struct.String %sc_result"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "@.fmt_int = private constant [5 x i8] c\"%ld\\0A\\00\""
  let s := s.emit "@.fmt_true = private constant [6 x i8] c\"true\\0A\\00\""
  let s := s.emit "@.fmt_false = private constant [7 x i8] c\"false\\0A\\00\""
  let s := s.emit ""
  let s := s.emit "define void @print_int(i64 %x) {"
  let s := s.emit "  %fmt = getelementptr [5 x i8], ptr @.fmt_int, i64 0, i64 0"
  let s := s.emit "  call i32 (ptr, ...) @printf(ptr %fmt, i64 %x)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "define void @print_bool(i1 %x) {"
  let s := s.emit "  br i1 %x, label %true_br, label %false_br"
  let s := s.emit "true_br:"
  let s := s.emit "  %fmt_t = getelementptr [6 x i8], ptr @.fmt_true, i64 0, i64 0"
  let s := s.emit "  call i32 (ptr, ...) @printf(ptr %fmt_t)"
  let s := s.emit "  br label %done_br"
  let s := s.emit "false_br:"
  let s := s.emit "  %fmt_f = getelementptr [7 x i8], ptr @.fmt_false, i64 0, i64 0"
  let s := s.emit "  call i32 (ptr, ...) @printf(ptr %fmt_f)"
  let s := s.emit "  br label %done_br"
  let s := s.emit "done_br:"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- read_file / write_file
  let s := s.emit "@.read_mode = private constant [2 x i8] c\"r\\00\""
  let s := s.emit "@.write_mode = private constant [2 x i8] c\"w\\00\""
  let s := s.emit ""
  let s := s.emit "define %struct.String @read_file(ptr %path) {"
  let s := s.emit "  %path_data_ptr = getelementptr inbounds %struct.String, ptr %path, i32 0, i32 0"
  let s := s.emit "  %path_data = load ptr, ptr %path_data_ptr"
  let s := s.emit "  %path_len_ptr = getelementptr inbounds %struct.String, ptr %path, i32 0, i32 1"
  let s := s.emit "  %path_len = load i64, ptr %path_len_ptr"
  let s := s.emit "  %path_buf_sz = add i64 %path_len, 1"
  let s := s.emit "  %path_buf = call ptr @malloc(i64 %path_buf_sz)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %path_buf, ptr %path_data, i64 %path_len, i1 false)"
  let s := s.emit "  %null_pos = getelementptr i8, ptr %path_buf, i64 %path_len"
  let s := s.emit "  store i8 0, ptr %null_pos"
  let s := s.emit "  %mode_r = getelementptr [2 x i8], ptr @.read_mode, i64 0, i64 0"
  let s := s.emit "  %fp = call ptr @fopen(ptr %path_buf, ptr %mode_r)"
  let s := s.emit "  call void @free(ptr %path_buf)"
  let s := s.emit "  %seek1 = call i32 @fseek(ptr %fp, i64 0, i32 2)"
  let s := s.emit "  %size = call i64 @ftell(ptr %fp)"
  let s := s.emit "  %seek2 = call i32 @fseek(ptr %fp, i64 0, i32 0)"
  let s := s.emit "  %buf = call ptr @malloc(i64 %size)"
  let s := s.emit "  %bytes_read = call i64 @fread(ptr %buf, i64 1, i64 %size, ptr %fp)"
  let s := s.emit "  %unused_close = call i32 @fclose(ptr %fp)"
  let s := s.emit "  %str_alloca = alloca %struct.String"
  let s := s.emit "  %str_data_ptr = getelementptr inbounds %struct.String, ptr %str_alloca, i32 0, i32 0"
  let s := s.emit "  store ptr %buf, ptr %str_data_ptr"
  let s := s.emit "  %str_len_ptr = getelementptr inbounds %struct.String, ptr %str_alloca, i32 0, i32 1"
  let s := s.emit "  store i64 %bytes_read, ptr %str_len_ptr"
  let s := s.emit "  %result = load %struct.String, ptr %str_alloca"
  let s := s.emit "  ret %struct.String %result"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "define i64 @write_file(ptr %path, ptr %data) {"
  let s := s.emit "  %wf_path_data_ptr = getelementptr inbounds %struct.String, ptr %path, i32 0, i32 0"
  let s := s.emit "  %wf_path_data = load ptr, ptr %wf_path_data_ptr"
  let s := s.emit "  %wf_path_len_ptr = getelementptr inbounds %struct.String, ptr %path, i32 0, i32 1"
  let s := s.emit "  %wf_path_len = load i64, ptr %wf_path_len_ptr"
  let s := s.emit "  %wf_buf_sz = add i64 %wf_path_len, 1"
  let s := s.emit "  %wf_buf = call ptr @malloc(i64 %wf_buf_sz)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %wf_buf, ptr %wf_path_data, i64 %wf_path_len, i1 false)"
  let s := s.emit "  %wf_null_pos = getelementptr i8, ptr %wf_buf, i64 %wf_path_len"
  let s := s.emit "  store i8 0, ptr %wf_null_pos"
  let s := s.emit "  %mode_w = getelementptr [2 x i8], ptr @.write_mode, i64 0, i64 0"
  let s := s.emit "  %wf_fp = call ptr @fopen(ptr %wf_buf, ptr %mode_w)"
  let s := s.emit "  call void @free(ptr %wf_buf)"
  let s := s.emit "  %wf_data_ptr = getelementptr inbounds %struct.String, ptr %data, i32 0, i32 0"
  let s := s.emit "  %wf_data_buf = load ptr, ptr %wf_data_ptr"
  let s := s.emit "  %wf_data_len_ptr = getelementptr inbounds %struct.String, ptr %data, i32 0, i32 1"
  let s := s.emit "  %wf_data_len = load i64, ptr %wf_data_len_ptr"
  let s := s.emit "  %wf_written = call i64 @fwrite(ptr %wf_data_buf, i64 1, i64 %wf_data_len, ptr %wf_fp)"
  let s := s.emit "  %wf_unused = call i32 @fclose(ptr %wf_fp)"
  let s := s.emit "  ret i64 %wf_written"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_slice
  let s := s.emit "define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {"
  let s := s.emit "  %len_ptr.ss = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len.ss = load i64, ptr %len_ptr.ss"
  let s := s.emit "  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)"
  let s := s.emit "  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)"
  let s := s.emit "  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)"
  let s := s.emit "  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)"
  let s := s.emit "  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)"
  let s := s.emit "  %slice_len = sub i64 %e_final, %s_min"
  let s := s.emit "  %slice_buf = call ptr @malloc(i64 %slice_len)"
  let s := s.emit "  %data_ptr.ss = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data.ss = load ptr, ptr %data_ptr.ss"
  let s := s.emit "  %src = getelementptr i8, ptr %data.ss, i64 %s_min"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)"
  let s := s.emit "  %res.ss = alloca %struct.String"
  let s := s.emit "  %res_d.ss = getelementptr inbounds %struct.String, ptr %res.ss, i32 0, i32 0"
  let s := s.emit "  store ptr %slice_buf, ptr %res_d.ss"
  let s := s.emit "  %res_l.ss = getelementptr inbounds %struct.String, ptr %res.ss, i32 0, i32 1"
  let s := s.emit "  store i64 %slice_len, ptr %res_l.ss"
  let s := s.emit "  %result.ss = load %struct.String, ptr %res.ss"
  let s := s.emit "  ret %struct.String %result.ss"
  let s := s.emit "}"
  let s := s.emit "declare i64 @llvm.smax.i64(i64, i64)"
  let s := s.emit "declare i64 @llvm.smin.i64(i64, i64)"
  let s := s.emit ""
  -- string_char_at
  let s := s.emit "define i64 @string_char_at(ptr %s, i64 %index) {"
  let s := s.emit "  %len_ptr.sca = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len.sca = load i64, ptr %len_ptr.sca"
  let s := s.emit "  %neg = icmp slt i64 %index, 0"
  let s := s.emit "  %oob = icmp sge i64 %index, %len.sca"
  let s := s.emit "  %bad = or i1 %neg, %oob"
  let s := s.emit "  br i1 %bad, label %ret_neg, label %ok_idx"
  let s := s.emit "ret_neg:"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "ok_idx:"
  let s := s.emit "  %data_ptr.sca = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data.sca = load ptr, ptr %data_ptr.sca"
  let s := s.emit "  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index"
  let s := s.emit "  %byte = load i8, ptr %char_ptr"
  let s := s.emit "  %char = zext i8 %byte to i64"
  let s := s.emit "  ret i64 %char"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_contains
  let s := s.emit "define i1 @string_contains(ptr %haystack, ptr %needle) {"
  let s := s.emit "  %h_data_ptr = getelementptr inbounds %struct.String, ptr %haystack, i32 0, i32 0"
  let s := s.emit "  %h_data = load ptr, ptr %h_data_ptr"
  let s := s.emit "  %h_len_ptr = getelementptr inbounds %struct.String, ptr %haystack, i32 0, i32 1"
  let s := s.emit "  %h_len = load i64, ptr %h_len_ptr"
  let s := s.emit "  %n_data_ptr = getelementptr inbounds %struct.String, ptr %needle, i32 0, i32 0"
  let s := s.emit "  %n_data = load ptr, ptr %n_data_ptr"
  let s := s.emit "  %n_len_ptr = getelementptr inbounds %struct.String, ptr %needle, i32 0, i32 1"
  let s := s.emit "  %n_len = load i64, ptr %n_len_ptr"
  let s := s.emit "  %n_empty = icmp eq i64 %n_len, 0"
  let s := s.emit "  br i1 %n_empty, label %found, label %check_len"
  let s := s.emit "check_len:"
  let s := s.emit "  %too_long = icmp ugt i64 %n_len, %h_len"
  let s := s.emit "  br i1 %too_long, label %not_found, label %loop_start"
  let s := s.emit "loop_start:"
  let s := s.emit "  %max_i = sub i64 %h_len, %n_len"
  let s := s.emit "  br label %loop"
  let s := s.emit "loop:"
  let s := s.emit "  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]"
  let s := s.emit "  %h_ptr = getelementptr i8, ptr %h_data, i64 %i"
  let s := s.emit "  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)"
  let s := s.emit "  %match = icmp eq i32 %cmp, 0"
  let s := s.emit "  br i1 %match, label %found, label %loop_cont"
  let s := s.emit "loop_cont:"
  let s := s.emit "  %i_next = add i64 %i, 1"
  let s := s.emit "  %done = icmp ugt i64 %i_next, %max_i"
  let s := s.emit "  br i1 %done, label %not_found, label %loop"
  let s := s.emit "found:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "not_found:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_eq
  let s := s.emit "define i1 @string_eq(ptr %a, ptr %b) {"
  let s := s.emit "  %a_len_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 1"
  let s := s.emit "  %a_len = load i64, ptr %a_len_ptr"
  let s := s.emit "  %b_len_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 1"
  let s := s.emit "  %b_len = load i64, ptr %b_len_ptr"
  let s := s.emit "  %len_eq = icmp eq i64 %a_len, %b_len"
  let s := s.emit "  br i1 %len_eq, label %cmp_data, label %not_eq"
  let s := s.emit "cmp_data:"
  let s := s.emit "  %zero_len = icmp eq i64 %a_len, 0"
  let s := s.emit "  br i1 %zero_len, label %eq, label %do_cmp"
  let s := s.emit "do_cmp:"
  let s := s.emit "  %a_data_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 0"
  let s := s.emit "  %a_data = load ptr, ptr %a_data_ptr"
  let s := s.emit "  %b_data_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 0"
  let s := s.emit "  %b_data = load ptr, ptr %b_data_ptr"
  let s := s.emit "  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)"
  let s := s.emit "  %eq_data = icmp eq i32 %cmp_res, 0"
  let s := s.emit "  br i1 %eq_data, label %eq, label %not_eq"
  let s := s.emit "eq:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "not_eq:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "}"
  let s := s.emit ""
  s

/-- Emit LLVM IR for conversion and I/O builtins. -/
def genConversionBuiltins (s : CodegenState) : CodegenState :=
  -- int_to_string
  let s := s.emit "@.fmt_ld = private constant [4 x i8] c\"%ld\\00\""
  let s := s.emit "define %struct.String @int_to_string(i64 %n) {"
  let s := s.emit "  %buf = call ptr @malloc(i64 32)"
  let s := s.emit "  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0"
  let s := s.emit "  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)"
  let s := s.emit "  %wext = sext i32 %written to i64"
  let s := s.emit "  %res.its = alloca %struct.String"
  let s := s.emit "  %res_d.its = getelementptr inbounds %struct.String, ptr %res.its, i32 0, i32 0"
  let s := s.emit "  store ptr %buf, ptr %res_d.its"
  let s := s.emit "  %res_l.its = getelementptr inbounds %struct.String, ptr %res.its, i32 0, i32 1"
  let s := s.emit "  store i64 %wext, ptr %res_l.its"
  let s := s.emit "  %result.its = load %struct.String, ptr %res.its"
  let s := s.emit "  ret %struct.String %result.its"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_to_int — returns Result<Int, Int>
  let s := s.emit "define %enum.Result @string_to_int(ptr %s) {"
  let s := s.emit "  %sti_data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %sti_data = load ptr, ptr %sti_data_ptr"
  let s := s.emit "  %sti_len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %sti_len = load i64, ptr %sti_len_ptr"
  let s := s.emit "  %sti_buf_sz = add i64 %sti_len, 1"
  let s := s.emit "  %sti_buf = call ptr @malloc(i64 %sti_buf_sz)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)"
  let s := s.emit "  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len"
  let s := s.emit "  store i8 0, ptr %sti_null"
  let s := s.emit "  %endptr_alloca = alloca ptr"
  let s := s.emit "  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)"
  let s := s.emit "  %endptr = load ptr, ptr %endptr_alloca"
  let s := s.emit "  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len"
  let s := s.emit "  %valid = icmp eq ptr %endptr, %end_expected"
  let s := s.emit "  %empty_input = icmp eq i64 %sti_len, 0"
  let s := s.emit "  %not_empty = xor i1 %empty_input, true"
  let s := s.emit "  %final_ok = and i1 %valid, %not_empty"
  let s := s.emit "  call void @free(ptr %sti_buf)"
  let s := s.emit "  %res.sti = alloca %enum.Result"
  let s := s.emit "  br i1 %final_ok, label %sti_ok, label %sti_err"
  let s := s.emit "sti_ok:"
  let s := s.emit "  store i32 0, ptr %res.sti"
  let s := s.emit "  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8"
  let s := s.emit "  store i64 %sti_val, ptr %data_ptr.sti_ok"
  let s := s.emit "  br label %sti_done"
  let s := s.emit "sti_err:"
  let s := s.emit "  store i32 1, ptr %res.sti"
  let s := s.emit "  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8"
  let s := s.emit "  store i64 1, ptr %data_ptr.sti_err"
  let s := s.emit "  br label %sti_done"
  let s := s.emit "sti_done:"
  let s := s.emit "  %result.sti = load %enum.Result, ptr %res.sti"
  let s := s.emit "  ret %enum.Result %result.sti"
  let s := s.emit "}"
  let s := s.emit ""
  -- bool_to_string
  let s := s.emit "@.str_true = private constant [4 x i8] c\"true\""
  let s := s.emit "@.str_false = private constant [5 x i8] c\"false\""
  let s := s.emit "define %struct.String @bool_to_string(i1 %b) {"
  let s := s.emit "  br i1 %b, label %bts_true, label %bts_false"
  let s := s.emit "bts_true:"
  let s := s.emit "  %tbuf = call ptr @malloc(i64 4)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)"
  let s := s.emit "  %tres = alloca %struct.String"
  let s := s.emit "  %td = getelementptr inbounds %struct.String, ptr %tres, i32 0, i32 0"
  let s := s.emit "  store ptr %tbuf, ptr %td"
  let s := s.emit "  %tl = getelementptr inbounds %struct.String, ptr %tres, i32 0, i32 1"
  let s := s.emit "  store i64 4, ptr %tl"
  let s := s.emit "  %tresult = load %struct.String, ptr %tres"
  let s := s.emit "  ret %struct.String %tresult"
  let s := s.emit "bts_false:"
  let s := s.emit "  %fbuf = call ptr @malloc(i64 5)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)"
  let s := s.emit "  %fres = alloca %struct.String"
  let s := s.emit "  %fd = getelementptr inbounds %struct.String, ptr %fres, i32 0, i32 0"
  let s := s.emit "  store ptr %fbuf, ptr %fd"
  let s := s.emit "  %fl = getelementptr inbounds %struct.String, ptr %fres, i32 0, i32 1"
  let s := s.emit "  store i64 5, ptr %fl"
  let s := s.emit "  %fresult = load %struct.String, ptr %fres"
  let s := s.emit "  ret %struct.String %fresult"
  let s := s.emit "}"
  let s := s.emit ""
  -- float_to_string
  let s := s.emit "@.fmt_f = private constant [3 x i8] c\"%g\\00\""
  let s := s.emit "define %struct.String @float_to_string(double %f) {"
  let s := s.emit "  %fbuf.fts = call ptr @malloc(i64 64)"
  let s := s.emit "  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0"
  let s := s.emit "  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)"
  let s := s.emit "  %wext.fts = sext i32 %written.fts to i64"
  let s := s.emit "  %res.fts = alloca %struct.String"
  let s := s.emit "  %res_d.fts = getelementptr inbounds %struct.String, ptr %res.fts, i32 0, i32 0"
  let s := s.emit "  store ptr %fbuf.fts, ptr %res_d.fts"
  let s := s.emit "  %res_l.fts = getelementptr inbounds %struct.String, ptr %res.fts, i32 0, i32 1"
  let s := s.emit "  store i64 %wext.fts, ptr %res_l.fts"
  let s := s.emit "  %result.fts = load %struct.String, ptr %res.fts"
  let s := s.emit "  ret %struct.String %result.fts"
  let s := s.emit "}"
  let s := s.emit ""
  -- read_line
  let s := s.emit "define %struct.String @read_line() {"
  let s := s.emit "  %rl_buf = call ptr @malloc(i64 128)"
  let s := s.emit "  br label %rl_loop"
  let s := s.emit "rl_loop:"
  let s := s.emit "  %rl_pos = phi i64 [0, %0], [%rl_pos_next, %rl_store]"
  let s := s.emit "  %rl_cur_buf = phi ptr [%rl_buf, %0], [%rl_new_buf, %rl_store]"
  let s := s.emit "  %rl_cur_cap = phi i64 [128, %0], [%rl_new_cap, %rl_store]"
  let s := s.emit "  %rl_one = alloca i8"
  let s := s.emit "  %rl_n = call i64 @read(i32 0, ptr %rl_one, i64 1)"
  let s := s.emit "  %rl_eof = icmp sle i64 %rl_n, 0"
  let s := s.emit "  br i1 %rl_eof, label %rl_done, label %rl_got_char"
  let s := s.emit "rl_got_char:"
  let s := s.emit "  %rl_ch = load i8, ptr %rl_one"
  let s := s.emit "  %rl_is_nl = icmp eq i8 %rl_ch, 10"
  let s := s.emit "  br i1 %rl_is_nl, label %rl_done, label %rl_store"
  let s := s.emit "rl_store:"
  let s := s.emit "  %rl_need_grow = icmp uge i64 %rl_pos, %rl_cur_cap"
  let s := s.emit "  %rl_double_cap = mul i64 %rl_cur_cap, 2"
  let s := s.emit "  %rl_new_cap = select i1 %rl_need_grow, i64 %rl_double_cap, i64 %rl_cur_cap"
  let s := s.emit "  %rl_new_buf = call ptr @realloc(ptr %rl_cur_buf, i64 %rl_new_cap)"
  let s := s.emit "  %rl_dst = getelementptr i8, ptr %rl_new_buf, i64 %rl_pos"
  let s := s.emit "  store i8 %rl_ch, ptr %rl_dst"
  let s := s.emit "  %rl_pos_next = add i64 %rl_pos, 1"
  let s := s.emit "  br label %rl_loop"
  let s := s.emit "rl_done:"
  let s := s.emit "  %rl_final_buf = phi ptr [%rl_cur_buf, %rl_loop], [%rl_cur_buf, %rl_got_char]"
  let s := s.emit "  %rl_final_len = phi i64 [%rl_pos, %rl_loop], [%rl_pos, %rl_got_char]"
  let s := s.emit "  %rl_res = alloca %struct.String"
  let s := s.emit "  %rl_res_d = getelementptr inbounds %struct.String, ptr %rl_res, i32 0, i32 0"
  let s := s.emit "  store ptr %rl_final_buf, ptr %rl_res_d"
  let s := s.emit "  %rl_res_l = getelementptr inbounds %struct.String, ptr %rl_res, i32 0, i32 1"
  let s := s.emit "  store i64 %rl_final_len, ptr %rl_res_l"
  let s := s.emit "  %rl_result = load %struct.String, ptr %rl_res"
  let s := s.emit "  ret %struct.String %rl_result"
  let s := s.emit "}"
  let s := s.emit ""
  -- print_char
  let s := s.emit "define void @print_char(i64 %c) {"
  let s := s.emit "  %c32 = trunc i64 %c to i32"
  let s := s.emit "  %unused.pc = call i32 @putchar(i32 %c32)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- eprint_string
  let s := s.emit "define void @eprint_string(ptr %s) {"
  let s := s.emit "  %ep_data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %ep_data = load ptr, ptr %ep_data_ptr"
  let s := s.emit "  %ep_len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %ep_len = load i64, ptr %ep_len_ptr"
  let s := s.emit "  %unused.ep = call i64 @write(i32 2, ptr %ep_data, i64 %ep_len)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- get_env — returns Option<String>
  let s := s.emit "define %enum.Option @get_env(ptr %name) {"
  let s := s.emit "  %ge_data_ptr = getelementptr inbounds %struct.String, ptr %name, i32 0, i32 0"
  let s := s.emit "  %ge_data = load ptr, ptr %ge_data_ptr"
  let s := s.emit "  %ge_len_ptr = getelementptr inbounds %struct.String, ptr %name, i32 0, i32 1"
  let s := s.emit "  %ge_len = load i64, ptr %ge_len_ptr"
  let s := s.emit "  %ge_buf_sz = add i64 %ge_len, 1"
  let s := s.emit "  %ge_buf = call ptr @malloc(i64 %ge_buf_sz)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %ge_buf, ptr %ge_data, i64 %ge_len, i1 false)"
  let s := s.emit "  %ge_null = getelementptr i8, ptr %ge_buf, i64 %ge_len"
  let s := s.emit "  store i8 0, ptr %ge_null"
  let s := s.emit "  %ge_val = call ptr @getenv(ptr %ge_buf)"
  let s := s.emit "  call void @free(ptr %ge_buf)"
  let s := s.emit "  %ge_is_null = icmp eq ptr %ge_val, null"
  let s := s.emit "  %res.ge = alloca %enum.Option"
  let s := s.emit "  br i1 %ge_is_null, label %ge_none, label %ge_some"
  let s := s.emit "ge_some:"
  let s := s.emit "  store i32 0, ptr %res.ge"
  let s := s.emit "  %ge_vlen = call i64 @strlen(ptr %ge_val)"
  let s := s.emit "  %ge_vbuf = call ptr @malloc(i64 %ge_vlen)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %ge_vbuf, ptr %ge_val, i64 %ge_vlen, i1 false)"
  let s := s.emit "  %ge_data_area = getelementptr i8, ptr %res.ge, i64 8"
  let s := s.emit "  store ptr %ge_vbuf, ptr %ge_data_area"
  let s := s.emit "  %ge_len_area = getelementptr i8, ptr %ge_data_area, i64 8"
  let s := s.emit "  store i64 %ge_vlen, ptr %ge_len_area"
  let s := s.emit "  br label %ge_done"
  let s := s.emit "ge_none:"
  let s := s.emit "  store i32 1, ptr %res.ge"
  let s := s.emit "  br label %ge_done"
  let s := s.emit "ge_done:"
  let s := s.emit "  %result.ge = load %enum.Option, ptr %res.ge"
  let s := s.emit "  ret %enum.Option %result.ge"
  let s := s.emit "}"
  let s := s.emit ""
  -- exit_process
  let s := s.emit "define void @exit_process(i64 %code) {"
  let s := s.emit "  %code32 = trunc i64 %code to i32"
  let s := s.emit "  call void @exit(i32 %code32)"
  let s := s.emit "  unreachable"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_trim
  let s := s.emit "define %struct.String @string_trim(ptr %s) {"
  let s := s.emit "  %st_data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %st_data = load ptr, ptr %st_data_ptr"
  let s := s.emit "  %st_len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %st_len = load i64, ptr %st_len_ptr"
  let s := s.emit "  br label %trim_left"
  let s := s.emit "trim_left:"
  let s := s.emit "  %tl_i = phi i64 [0, %0], [%tl_next, %tl_ws]"
  let s := s.emit "  %tl_done = icmp uge i64 %tl_i, %st_len"
  let s := s.emit "  br i1 %tl_done, label %trim_result, label %tl_check"
  let s := s.emit "tl_check:"
  let s := s.emit "  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i"
  let s := s.emit "  %tl_ch = load i8, ptr %tl_ptr"
  let s := s.emit "  %tl_is_sp = icmp eq i8 %tl_ch, 32"
  let s := s.emit "  %tl_is_tab = icmp eq i8 %tl_ch, 9"
  let s := s.emit "  %tl_is_nl = icmp eq i8 %tl_ch, 10"
  let s := s.emit "  %tl_is_cr = icmp eq i8 %tl_ch, 13"
  let s := s.emit "  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab"
  let s := s.emit "  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr"
  let s := s.emit "  %tl_is_ws = or i1 %tl_w1, %tl_w2"
  let s := s.emit "  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init"
  let s := s.emit "tl_ws:"
  let s := s.emit "  %tl_next = add i64 %tl_i, 1"
  let s := s.emit "  br label %trim_left"
  let s := s.emit "trim_right_init:"
  let s := s.emit "  %tr_start = sub i64 %st_len, 1"
  let s := s.emit "  br label %trim_right"
  let s := s.emit "trim_right:"
  let s := s.emit "  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]"
  let s := s.emit "  %tr_done = icmp ult i64 %tr_i, %tl_i"
  let s := s.emit "  br i1 %tr_done, label %trim_result, label %tr_check"
  let s := s.emit "tr_check:"
  let s := s.emit "  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i"
  let s := s.emit "  %tr_ch = load i8, ptr %tr_ptr"
  let s := s.emit "  %tr_is_sp = icmp eq i8 %tr_ch, 32"
  let s := s.emit "  %tr_is_tab = icmp eq i8 %tr_ch, 9"
  let s := s.emit "  %tr_is_nl = icmp eq i8 %tr_ch, 10"
  let s := s.emit "  %tr_is_cr = icmp eq i8 %tr_ch, 13"
  let s := s.emit "  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab"
  let s := s.emit "  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr"
  let s := s.emit "  %tr_is_ws = or i1 %tr_w1, %tr_w2"
  let s := s.emit "  br i1 %tr_is_ws, label %tr_ws, label %trim_result"
  let s := s.emit "tr_ws:"
  let s := s.emit "  %tr_prev = sub i64 %tr_i, 1"
  let s := s.emit "  br label %trim_right"
  let s := s.emit "trim_result:"
  let s := s.emit "  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]"
  let s := s.emit "  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]"
  let s := s.emit "  %tr_right = add i64 %tr_right_raw, 1"
  let s := s.emit "  %tr_empty = icmp uge i64 %tr_left, %tr_right"
  let s := s.emit "  br i1 %tr_empty, label %trim_empty, label %trim_copy"
  let s := s.emit "trim_empty:"
  let s := s.emit "  %te_buf = call ptr @malloc(i64 1)"
  let s := s.emit "  %te_res = alloca %struct.String"
  let s := s.emit "  %te_d = getelementptr inbounds %struct.String, ptr %te_res, i32 0, i32 0"
  let s := s.emit "  store ptr %te_buf, ptr %te_d"
  let s := s.emit "  %te_l = getelementptr inbounds %struct.String, ptr %te_res, i32 0, i32 1"
  let s := s.emit "  store i64 0, ptr %te_l"
  let s := s.emit "  %te_result = load %struct.String, ptr %te_res"
  let s := s.emit "  ret %struct.String %te_result"
  let s := s.emit "trim_copy:"
  let s := s.emit "  %tc_len = sub i64 %tr_right, %tr_left"
  let s := s.emit "  %tc_buf = call ptr @malloc(i64 %tc_len)"
  let s := s.emit "  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)"
  let s := s.emit "  %tc_res = alloca %struct.String"
  let s := s.emit "  %tc_d = getelementptr inbounds %struct.String, ptr %tc_res, i32 0, i32 0"
  let s := s.emit "  store ptr %tc_buf, ptr %tc_d"
  let s := s.emit "  %tc_l = getelementptr inbounds %struct.String, ptr %tc_res, i32 0, i32 1"
  let s := s.emit "  store i64 %tc_len, ptr %tc_l"
  let s := s.emit "  %tc_result = load %struct.String, ptr %tc_res"
  let s := s.emit "  ret %struct.String %tc_result"
  let s := s.emit "}"
  let s := s.emit ""
  s

set_option maxRecDepth 8192 in
/-- Emit LLVM IR for HashMap helper functions (Int and String key variants). -/
def genHashMapFunctions (s : CodegenState) : CodegenState :=
  -- Helper: __hashmap_int_new(ptr map_out, i64 ksize, i64 vsize)
  -- Initializes a HashMap struct at map_out with capacity 16
  let s := s.emit "define void @__hashmap_int_new(ptr %mo, i64 %ks, i64 %vs) {"
  let s := s.emit "  %kb = mul i64 16, %ks"
  let s := s.emit "  %kbuf = call ptr @malloc(i64 %kb)"
  let s := s.emit "  %vb = mul i64 16, %vs"
  let s := s.emit "  %vbuf = call ptr @malloc(i64 %vb)"
  let s := s.emit "  %fbuf = call ptr @malloc(i64 16)"
  -- Zero flags
  let s := s.emit "  br label %zl"
  let s := s.emit "zl:"
  let s := s.emit "  %zi = phi i64 [ 0, %0 ], [ %zi1, %zl ]"
  let s := s.emit "  %zp = getelementptr i8, ptr %fbuf, i64 %zi"
  let s := s.emit "  store i8 0, ptr %zp"
  let s := s.emit "  %zi1 = add i64 %zi, 1"
  let s := s.emit "  %zd = icmp uge i64 %zi1, 16"
  let s := s.emit "  br i1 %zd, label %zx, label %zl"
  let s := s.emit "zx:"
  let s := s.emit "  %f0 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 0"
  let s := s.emit "  store ptr %kbuf, ptr %f0"
  let s := s.emit "  %f1 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 1"
  let s := s.emit "  store ptr %vbuf, ptr %f1"
  let s := s.emit "  %f2 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 2"
  let s := s.emit "  store ptr %fbuf, ptr %f2"
  let s := s.emit "  %f3 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 3"
  let s := s.emit "  store i64 0, ptr %f3"
  let s := s.emit "  %f4 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 4"
  let s := s.emit "  store i64 16, ptr %f4"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_str_new: same implementation as int (structure is identical)
  let s := s.emit "define void @__hashmap_str_new(ptr %mo, i64 %ks, i64 %vs) {"
  let s := s.emit "  %kb = mul i64 16, %ks"
  let s := s.emit "  %kbuf = call ptr @malloc(i64 %kb)"
  let s := s.emit "  %vb = mul i64 16, %vs"
  let s := s.emit "  %vbuf = call ptr @malloc(i64 %vb)"
  let s := s.emit "  %fbuf = call ptr @malloc(i64 16)"
  let s := s.emit "  br label %zl"
  let s := s.emit "zl:"
  let s := s.emit "  %zi = phi i64 [ 0, %0 ], [ %zi1, %zl ]"
  let s := s.emit "  %zp = getelementptr i8, ptr %fbuf, i64 %zi"
  let s := s.emit "  store i8 0, ptr %zp"
  let s := s.emit "  %zi1 = add i64 %zi, 1"
  let s := s.emit "  %zd = icmp uge i64 %zi1, 16"
  let s := s.emit "  br i1 %zd, label %zx, label %zl"
  let s := s.emit "zx:"
  let s := s.emit "  %f0 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 0"
  let s := s.emit "  store ptr %kbuf, ptr %f0"
  let s := s.emit "  %f1 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 1"
  let s := s.emit "  store ptr %vbuf, ptr %f1"
  let s := s.emit "  %f2 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 2"
  let s := s.emit "  store ptr %fbuf, ptr %f2"
  let s := s.emit "  %f3 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 3"
  let s := s.emit "  store i64 0, ptr %f3"
  let s := s.emit "  %f4 = getelementptr inbounds %struct.HashMap, ptr %mo, i32 0, i32 4"
  let s := s.emit "  store i64 16, ptr %f4"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- Int hash function: multiplicative hash with xorshift
  let s := s.emit "define i64 @__hash_int(i64 %k) {"
  let s := s.emit "  %m = mul i64 %k, -7046029254386353131"
  let s := s.emit "  %s = lshr i64 %m, 33"
  let s := s.emit "  %h = xor i64 %m, %s"
  let s := s.emit "  ret i64 %h"
  let s := s.emit "}"
  let s := s.emit ""
  -- String hash function: FNV-1a
  let s := s.emit "define i64 @__hash_str(ptr %sp) {"
  let s := s.emit "  %dp = getelementptr inbounds %struct.String, ptr %sp, i32 0, i32 0"
  let s := s.emit "  %d = load ptr, ptr %dp"
  let s := s.emit "  %lp = getelementptr inbounds %struct.String, ptr %sp, i32 0, i32 1"
  let s := s.emit "  %l = load i64, ptr %lp"
  let s := s.emit "  %empty = icmp eq i64 %l, 0"
  let s := s.emit "  br i1 %empty, label %done, label %loop"
  let s := s.emit "loop:"
  let s := s.emit "  %i = phi i64 [ 0, %0 ], [ %i1, %loop ]"
  let s := s.emit "  %h = phi i64 [ -3750763034362895579, %0 ], [ %h3, %loop ]"
  let s := s.emit "  %bp = getelementptr i8, ptr %d, i64 %i"
  let s := s.emit "  %b = load i8, ptr %bp"
  let s := s.emit "  %bx = zext i8 %b to i64"
  let s := s.emit "  %h2 = xor i64 %h, %bx"
  let s := s.emit "  %h3 = mul i64 %h2, 1099511628211"
  let s := s.emit "  %i1 = add i64 %i, 1"
  let s := s.emit "  %c = icmp uge i64 %i1, %l"
  let s := s.emit "  br i1 %c, label %done, label %loop"
  let s := s.emit "done:"
  let s := s.emit "  %r = phi i64 [ -3750763034362895579, %0 ], [ %h3, %loop ]"
  let s := s.emit "  ret i64 %r"
  let s := s.emit "}"
  let s := s.emit ""
  -- Int key equality
  let s := s.emit "define i1 @__keq_int(ptr %a, ptr %b, i64 %ks) {"
  let s := s.emit "  %av = load i64, ptr %a"
  let s := s.emit "  %bv = load i64, ptr %b"
  let s := s.emit "  %eq = icmp eq i64 %av, %bv"
  let s := s.emit "  ret i1 %eq"
  let s := s.emit "}"
  let s := s.emit ""
  -- String key equality (compare length then memcmp)
  let s := s.emit "define i1 @__keq_str(ptr %a, ptr %b, i64 %ks) {"
  let s := s.emit "  %alp = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 1"
  let s := s.emit "  %al = load i64, ptr %alp"
  let s := s.emit "  %blp = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 1"
  let s := s.emit "  %bl = load i64, ptr %blp"
  let s := s.emit "  %le = icmp eq i64 %al, %bl"
  let s := s.emit "  br i1 %le, label %cmp, label %ne"
  let s := s.emit "cmp:"
  let s := s.emit "  %adp = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 0"
  let s := s.emit "  %ad = load ptr, ptr %adp"
  let s := s.emit "  %bdp = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 0"
  let s := s.emit "  %bd = load ptr, ptr %bdp"
  let s := s.emit "  %mc = call i32 @memcmp(ptr %ad, ptr %bd, i64 %al)"
  let s := s.emit "  %eq = icmp eq i32 %mc, 0"
  let s := s.emit "  br label %done"
  let s := s.emit "ne:"
  let s := s.emit "  br label %done"
  let s := s.emit "done:"
  let s := s.emit "  %r = phi i1 [ %eq, %cmp ], [ false, %ne ]"
  let s := s.emit "  ret i1 %r"
  let s := s.emit "}"
  let s := s.emit ""
  -- Generic insert: __hashmap_int_insert(ptr map, ptr key, ptr val, i64 ksize, i64 vsize)
  -- Uses __hash_int for hashing, __keq_int for comparison
  let s := s.emit "define void @__hashmap_int_insert(ptr %m, ptr %key, ptr %val, i64 %ks, i64 %vs) {"
  let s := s.emit "  %lenp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 3"
  let s := s.emit "  %len = load i64, ptr %lenp"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  -- Check load factor: len*4 > cap*3
  let s := s.emit "  %l4 = mul i64 %len, 4"
  let s := s.emit "  %c3 = mul i64 %cap, 3"
  let s := s.emit "  %ng = icmp ugt i64 %l4, %c3"
  let s := s.emit "  br i1 %ng, label %grow, label %ins"
  let s := s.emit "grow:"
  let s := s.emit "  %nc = mul i64 %cap, 2"
  let s := s.emit "  %nkb = mul i64 %nc, %ks"
  let s := s.emit "  %nkbuf = call ptr @malloc(i64 %nkb)"
  let s := s.emit "  %nvb = mul i64 %nc, %vs"
  let s := s.emit "  %nvbuf = call ptr @malloc(i64 %nvb)"
  let s := s.emit "  %nfbuf = call ptr @malloc(i64 %nc)"
  -- Zero new flags
  let s := s.emit "  br label %gz"
  let s := s.emit "gz:"
  let s := s.emit "  %gi = phi i64 [ 0, %grow ], [ %gi1, %gz ]"
  let s := s.emit "  %gp = getelementptr i8, ptr %nfbuf, i64 %gi"
  let s := s.emit "  store i8 0, ptr %gp"
  let s := s.emit "  %gi1 = add i64 %gi, 1"
  let s := s.emit "  %gd = icmp uge i64 %gi1, %nc"
  let s := s.emit "  br i1 %gd, label %rehash, label %gz"
  -- Rehash old entries into new buffers
  let s := s.emit "rehash:"
  let s := s.emit "  %okp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %okb = load ptr, ptr %okp"
  let s := s.emit "  %ovp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %ovb = load ptr, ptr %ovp"
  let s := s.emit "  %ofp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %ofb = load ptr, ptr %ofp"
  let s := s.emit "  %nm = sub i64 %nc, 1"
  let s := s.emit "  br label %rl"
  let s := s.emit "rl:"
  let s := s.emit "  %ri = phi i64 [ 0, %rehash ], [ %ri1, %rnext ]"
  let s := s.emit "  %rfp = getelementptr i8, ptr %ofb, i64 %ri"
  let s := s.emit "  %rf = load i8, ptr %rfp"
  let s := s.emit "  %rocc = icmp eq i8 %rf, 1"
  let s := s.emit "  br i1 %rocc, label %rins, label %rnext"
  let s := s.emit "rins:"
  let s := s.emit "  %rko = mul i64 %ri, %ks"
  let s := s.emit "  %rkp = getelementptr i8, ptr %okb, i64 %rko"
  let s := s.emit "  %rkv = load i64, ptr %rkp"
  let s := s.emit "  %rh = call i64 @__hash_int(i64 %rkv)"
  let s := s.emit "  %rs = and i64 %rh, %nm"
  let s := s.emit "  br label %rpl"
  let s := s.emit "rpl:"
  let s := s.emit "  %rj = phi i64 [ %rs, %rins ], [ %rj1w, %rpl ]"
  let s := s.emit "  %rpfp = getelementptr i8, ptr %nfbuf, i64 %rj"
  let s := s.emit "  %rpf = load i8, ptr %rpfp"
  let s := s.emit "  %rpe = icmp eq i8 %rpf, 0"
  let s := s.emit "  %rj1 = add i64 %rj, 1"
  let s := s.emit "  %rj1w = and i64 %rj1, %nm"
  let s := s.emit "  br i1 %rpe, label %rstore, label %rpl"
  let s := s.emit "rstore:"
  let s := s.emit "  %nko = mul i64 %rj, %ks"
  let s := s.emit "  %nkp = getelementptr i8, ptr %nkbuf, i64 %nko"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %nkp, ptr %rkp, i64 %ks, i1 false)"
  let s := s.emit "  %rvo = mul i64 %ri, %vs"
  let s := s.emit "  %rvp = getelementptr i8, ptr %ovb, i64 %rvo"
  let s := s.emit "  %nvo = mul i64 %rj, %vs"
  let s := s.emit "  %nvp = getelementptr i8, ptr %nvbuf, i64 %nvo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %nvp, ptr %rvp, i64 %vs, i1 false)"
  let s := s.emit "  store i8 1, ptr %rpfp"
  let s := s.emit "  br label %rnext"
  let s := s.emit "rnext:"
  let s := s.emit "  %ri1 = add i64 %ri, 1"
  let s := s.emit "  %rd = icmp uge i64 %ri1, %cap"
  let s := s.emit "  br i1 %rd, label %rdone, label %rl"
  let s := s.emit "rdone:"
  let s := s.emit "  call void @free(ptr %okb)"
  let s := s.emit "  call void @free(ptr %ovb)"
  let s := s.emit "  call void @free(ptr %ofb)"
  let s := s.emit "  store ptr %nkbuf, ptr %okp"
  let s := s.emit "  store ptr %nvbuf, ptr %ovp"
  let s := s.emit "  store ptr %nfbuf, ptr %ofp"
  let s := s.emit "  store i64 %nc, ptr %capp"
  let s := s.emit "  br label %ins"
  -- Insert the actual key/value
  let s := s.emit "ins:"
  let s := s.emit "  %ic = load i64, ptr %capp"
  let s := s.emit "  %im = sub i64 %ic, 1"
  let s := s.emit "  %ikp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %ikb = load ptr, ptr %ikp2"
  let s := s.emit "  %ivp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %ivb = load ptr, ptr %ivp2"
  let s := s.emit "  %ifp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %ifb = load ptr, ptr %ifp2"
  let s := s.emit "  %ikv = load i64, ptr %key"
  let s := s.emit "  %ih = call i64 @__hash_int(i64 %ikv)"
  let s := s.emit "  %is = and i64 %ih, %im"
  let s := s.emit "  br label %ipl"
  let s := s.emit "ipl:"
  let s := s.emit "  %ij = phi i64 [ %is, %ins ], [ %ij1w, %ipc ]"
  let s := s.emit "  %ipfp = getelementptr i8, ptr %ifb, i64 %ij"
  let s := s.emit "  %ipf = load i8, ptr %ipfp"
  let s := s.emit "  %ipe = icmp ne i8 %ipf, 1"
  let s := s.emit "  br i1 %ipe, label %istore, label %imatch"
  let s := s.emit "imatch:"
  let s := s.emit "  %iko = mul i64 %ij, %ks"
  let s := s.emit "  %ikpp = getelementptr i8, ptr %ikb, i64 %iko"
  let s := s.emit "  %ieq = call i1 @__keq_int(ptr %ikpp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %ieq, label %istore, label %ipc"
  let s := s.emit "ipc:"
  let s := s.emit "  %ij1 = add i64 %ij, 1"
  let s := s.emit "  %ij1w = and i64 %ij1, %im"
  let s := s.emit "  br label %ipl"
  let s := s.emit "istore:"
  let s := s.emit "  %wo = icmp eq i8 %ipf, 1"
  let s := s.emit "  %sko = mul i64 %ij, %ks"
  let s := s.emit "  %skp = getelementptr i8, ptr %ikb, i64 %sko"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %skp, ptr %key, i64 %ks, i1 false)"
  let s := s.emit "  %svo = mul i64 %ij, %vs"
  let s := s.emit "  %svp = getelementptr i8, ptr %ivb, i64 %svo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %svp, ptr %val, i64 %vs, i1 false)"
  let s := s.emit "  store i8 1, ptr %ipfp"
  let s := s.emit "  %cl = load i64, ptr %lenp"
  let s := s.emit "  %nl = add i64 %cl, 1"
  let s := s.emit "  %sl = select i1 %wo, i64 %cl, i64 %nl"
  let s := s.emit "  store i64 %sl, ptr %lenp"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_str_insert: same structure but uses __hash_str and __keq_str
  let s := s.emit "define void @__hashmap_str_insert(ptr %m, ptr %key, ptr %val, i64 %ks, i64 %vs) {"
  let s := s.emit "  %lenp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 3"
  let s := s.emit "  %len = load i64, ptr %lenp"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %l4 = mul i64 %len, 4"
  let s := s.emit "  %c3 = mul i64 %cap, 3"
  let s := s.emit "  %ng = icmp ugt i64 %l4, %c3"
  let s := s.emit "  br i1 %ng, label %grow, label %ins"
  let s := s.emit "grow:"
  let s := s.emit "  %nc = mul i64 %cap, 2"
  let s := s.emit "  %nkb = mul i64 %nc, %ks"
  let s := s.emit "  %nkbuf = call ptr @malloc(i64 %nkb)"
  let s := s.emit "  %nvb = mul i64 %nc, %vs"
  let s := s.emit "  %nvbuf = call ptr @malloc(i64 %nvb)"
  let s := s.emit "  %nfbuf = call ptr @malloc(i64 %nc)"
  let s := s.emit "  br label %gz"
  let s := s.emit "gz:"
  let s := s.emit "  %gi = phi i64 [ 0, %grow ], [ %gi1, %gz ]"
  let s := s.emit "  %gp = getelementptr i8, ptr %nfbuf, i64 %gi"
  let s := s.emit "  store i8 0, ptr %gp"
  let s := s.emit "  %gi1 = add i64 %gi, 1"
  let s := s.emit "  %gd = icmp uge i64 %gi1, %nc"
  let s := s.emit "  br i1 %gd, label %rehash, label %gz"
  let s := s.emit "rehash:"
  let s := s.emit "  %okp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %okb = load ptr, ptr %okp"
  let s := s.emit "  %ovp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %ovb = load ptr, ptr %ovp"
  let s := s.emit "  %ofp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %ofb = load ptr, ptr %ofp"
  let s := s.emit "  %nm = sub i64 %nc, 1"
  let s := s.emit "  br label %rl"
  let s := s.emit "rl:"
  let s := s.emit "  %ri = phi i64 [ 0, %rehash ], [ %ri1, %rnext ]"
  let s := s.emit "  %rfp = getelementptr i8, ptr %ofb, i64 %ri"
  let s := s.emit "  %rf = load i8, ptr %rfp"
  let s := s.emit "  %rocc = icmp eq i8 %rf, 1"
  let s := s.emit "  br i1 %rocc, label %rins, label %rnext"
  let s := s.emit "rins:"
  let s := s.emit "  %rko = mul i64 %ri, %ks"
  let s := s.emit "  %rkp = getelementptr i8, ptr %okb, i64 %rko"
  let s := s.emit "  %rh = call i64 @__hash_str(ptr %rkp)"
  let s := s.emit "  %rs = and i64 %rh, %nm"
  let s := s.emit "  br label %rpl"
  let s := s.emit "rpl:"
  let s := s.emit "  %rj = phi i64 [ %rs, %rins ], [ %rj1w, %rpl ]"
  let s := s.emit "  %rpfp = getelementptr i8, ptr %nfbuf, i64 %rj"
  let s := s.emit "  %rpf = load i8, ptr %rpfp"
  let s := s.emit "  %rpe = icmp eq i8 %rpf, 0"
  let s := s.emit "  %rj1 = add i64 %rj, 1"
  let s := s.emit "  %rj1w = and i64 %rj1, %nm"
  let s := s.emit "  br i1 %rpe, label %rstore, label %rpl"
  let s := s.emit "rstore:"
  let s := s.emit "  %nko = mul i64 %rj, %ks"
  let s := s.emit "  %nkp = getelementptr i8, ptr %nkbuf, i64 %nko"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %nkp, ptr %rkp, i64 %ks, i1 false)"
  let s := s.emit "  %rvo = mul i64 %ri, %vs"
  let s := s.emit "  %rvp = getelementptr i8, ptr %ovb, i64 %rvo"
  let s := s.emit "  %nvo = mul i64 %rj, %vs"
  let s := s.emit "  %nvp = getelementptr i8, ptr %nvbuf, i64 %nvo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %nvp, ptr %rvp, i64 %vs, i1 false)"
  let s := s.emit "  store i8 1, ptr %rpfp"
  let s := s.emit "  br label %rnext"
  let s := s.emit "rnext:"
  let s := s.emit "  %ri1 = add i64 %ri, 1"
  let s := s.emit "  %rd = icmp uge i64 %ri1, %cap"
  let s := s.emit "  br i1 %rd, label %rdone, label %rl"
  let s := s.emit "rdone:"
  let s := s.emit "  call void @free(ptr %okb)"
  let s := s.emit "  call void @free(ptr %ovb)"
  let s := s.emit "  call void @free(ptr %ofb)"
  let s := s.emit "  store ptr %nkbuf, ptr %okp"
  let s := s.emit "  store ptr %nvbuf, ptr %ovp"
  let s := s.emit "  store ptr %nfbuf, ptr %ofp"
  let s := s.emit "  store i64 %nc, ptr %capp"
  let s := s.emit "  br label %ins"
  let s := s.emit "ins:"
  let s := s.emit "  %ic = load i64, ptr %capp"
  let s := s.emit "  %im = sub i64 %ic, 1"
  let s := s.emit "  %ikp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %ikb = load ptr, ptr %ikp2"
  let s := s.emit "  %ivp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %ivb = load ptr, ptr %ivp2"
  let s := s.emit "  %ifp2 = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %ifb = load ptr, ptr %ifp2"
  let s := s.emit "  %ih = call i64 @__hash_str(ptr %key)"
  let s := s.emit "  %is = and i64 %ih, %im"
  let s := s.emit "  br label %ipl"
  let s := s.emit "ipl:"
  let s := s.emit "  %ij = phi i64 [ %is, %ins ], [ %ij1w, %ipc ]"
  let s := s.emit "  %ipfp = getelementptr i8, ptr %ifb, i64 %ij"
  let s := s.emit "  %ipf = load i8, ptr %ipfp"
  let s := s.emit "  %ipe = icmp ne i8 %ipf, 1"
  let s := s.emit "  br i1 %ipe, label %istore, label %imatch"
  let s := s.emit "imatch:"
  let s := s.emit "  %iko = mul i64 %ij, %ks"
  let s := s.emit "  %ikpp = getelementptr i8, ptr %ikb, i64 %iko"
  let s := s.emit "  %ieq = call i1 @__keq_str(ptr %ikpp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %ieq, label %istore, label %ipc"
  let s := s.emit "ipc:"
  let s := s.emit "  %ij1 = add i64 %ij, 1"
  let s := s.emit "  %ij1w = and i64 %ij1, %im"
  let s := s.emit "  br label %ipl"
  let s := s.emit "istore:"
  let s := s.emit "  %wo = icmp eq i8 %ipf, 1"
  let s := s.emit "  %sko = mul i64 %ij, %ks"
  let s := s.emit "  %skp = getelementptr i8, ptr %ikb, i64 %sko"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %skp, ptr %key, i64 %ks, i1 false)"
  let s := s.emit "  %svo = mul i64 %ij, %vs"
  let s := s.emit "  %svp = getelementptr i8, ptr %ivb, i64 %svo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %svp, ptr %val, i64 %vs, i1 false)"
  let s := s.emit "  store i8 1, ptr %ipfp"
  let s := s.emit "  %cl = load i64, ptr %lenp"
  let s := s.emit "  %nl = add i64 %cl, 1"
  let s := s.emit "  %sl = select i1 %wo, i64 %cl, i64 %nl"
  let s := s.emit "  store i64 %sl, ptr %lenp"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_int_get(ptr map, ptr key, ptr result_opt, i64 ks, i64 vs)
  -- Writes Option to result_opt: tag=0 (Some) + payload, or tag=1 (None)
  let s := s.emit "define void @__hashmap_int_get(ptr %m, ptr %key, ptr %opt, i64 %ks, i64 %vs) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %vbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %vb = load ptr, ptr %vbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %kv = load i64, ptr %key"
  let s := s.emit "  %h = call i64 @__hash_int(i64 %kv)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_int(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  store i32 1, ptr %opt"
  let s := s.emit "  ret void"
  let s := s.emit "found:"
  let s := s.emit "  store i32 0, ptr %opt"
  let s := s.emit "  %pp = getelementptr i8, ptr %opt, i64 8"
  let s := s.emit "  %vo = mul i64 %j, %vs"
  let s := s.emit "  %vp = getelementptr i8, ptr %vb, i64 %vo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %pp, ptr %vp, i64 %vs, i1 false)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_str_get: same but with __hash_str / __keq_str
  let s := s.emit "define void @__hashmap_str_get(ptr %m, ptr %key, ptr %opt, i64 %ks, i64 %vs) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %vbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %vb = load ptr, ptr %vbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %h = call i64 @__hash_str(ptr %key)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_str(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  store i32 1, ptr %opt"
  let s := s.emit "  ret void"
  let s := s.emit "found:"
  let s := s.emit "  store i32 0, ptr %opt"
  let s := s.emit "  %pp = getelementptr i8, ptr %opt, i64 8"
  let s := s.emit "  %vo = mul i64 %j, %vs"
  let s := s.emit "  %vp = getelementptr i8, ptr %vb, i64 %vo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %pp, ptr %vp, i64 %vs, i1 false)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_int_contains(ptr map, ptr key, i64 ks) -> i1
  let s := s.emit "define i1 @__hashmap_int_contains(ptr %m, ptr %key, i64 %ks) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %kv = load i64, ptr %key"
  let s := s.emit "  %h = call i64 @__hash_int(i64 %kv)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_int(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "found:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_str_contains
  let s := s.emit "define i1 @__hashmap_str_contains(ptr %m, ptr %key, i64 %ks) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %h = call i64 @__hash_str(ptr %key)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_str(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "found:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_int_remove: like get but sets flag to tombstone and decrements len
  let s := s.emit "define void @__hashmap_int_remove(ptr %m, ptr %key, ptr %opt, i64 %ks, i64 %vs) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %vbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %vb = load ptr, ptr %vbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %kv = load i64, ptr %key"
  let s := s.emit "  %h = call i64 @__hash_int(i64 %kv)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_int(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  store i32 1, ptr %opt"
  let s := s.emit "  ret void"
  let s := s.emit "found:"
  let s := s.emit "  store i32 0, ptr %opt"
  let s := s.emit "  %pp = getelementptr i8, ptr %opt, i64 8"
  let s := s.emit "  %vo = mul i64 %j, %vs"
  let s := s.emit "  %vp = getelementptr i8, ptr %vb, i64 %vo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %pp, ptr %vp, i64 %vs, i1 false)"
  let s := s.emit "  store i8 2, ptr %fp"
  let s := s.emit "  %lp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 3"
  let s := s.emit "  %l = load i64, ptr %lp"
  let s := s.emit "  %l1 = sub i64 %l, 1"
  let s := s.emit "  store i64 %l1, ptr %lp"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- __hashmap_str_remove
  let s := s.emit "define void @__hashmap_str_remove(ptr %m, ptr %key, ptr %opt, i64 %ks, i64 %vs) {"
  let s := s.emit "  %capp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 4"
  let s := s.emit "  %cap = load i64, ptr %capp"
  let s := s.emit "  %mask = sub i64 %cap, 1"
  let s := s.emit "  %kbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 0"
  let s := s.emit "  %kb = load ptr, ptr %kbp"
  let s := s.emit "  %vbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 1"
  let s := s.emit "  %vb = load ptr, ptr %vbp"
  let s := s.emit "  %fbp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 2"
  let s := s.emit "  %fb = load ptr, ptr %fbp"
  let s := s.emit "  %h = call i64 @__hash_str(ptr %key)"
  let s := s.emit "  %s = and i64 %h, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "pl:"
  let s := s.emit "  %j = phi i64 [ %s, %0 ], [ %j1w, %pc ]"
  let s := s.emit "  %fp = getelementptr i8, ptr %fb, i64 %j"
  let s := s.emit "  %f = load i8, ptr %fp"
  let s := s.emit "  %empty = icmp eq i8 %f, 0"
  let s := s.emit "  br i1 %empty, label %nf, label %occ"
  let s := s.emit "occ:"
  let s := s.emit "  %isocc = icmp eq i8 %f, 1"
  let s := s.emit "  br i1 %isocc, label %ck, label %pc"
  let s := s.emit "ck:"
  let s := s.emit "  %ko = mul i64 %j, %ks"
  let s := s.emit "  %kp = getelementptr i8, ptr %kb, i64 %ko"
  let s := s.emit "  %eq = call i1 @__keq_str(ptr %kp, ptr %key, i64 %ks)"
  let s := s.emit "  br i1 %eq, label %found, label %pc"
  let s := s.emit "pc:"
  let s := s.emit "  %j1 = add i64 %j, 1"
  let s := s.emit "  %j1w = and i64 %j1, %mask"
  let s := s.emit "  br label %pl"
  let s := s.emit "nf:"
  let s := s.emit "  store i32 1, ptr %opt"
  let s := s.emit "  ret void"
  let s := s.emit "found:"
  let s := s.emit "  store i32 0, ptr %opt"
  let s := s.emit "  %pp = getelementptr i8, ptr %opt, i64 8"
  let s := s.emit "  %vo = mul i64 %j, %vs"
  let s := s.emit "  %vp = getelementptr i8, ptr %vb, i64 %vo"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %pp, ptr %vp, i64 %vs, i1 false)"
  let s := s.emit "  store i8 2, ptr %fp"
  let s := s.emit "  %lp = getelementptr inbounds %struct.HashMap, ptr %m, i32 0, i32 3"
  let s := s.emit "  %l = load i64, ptr %lp"
  let s := s.emit "  %l1 = sub i64 %l, 1"
  let s := s.emit "  store i64 %l1, ptr %lp"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  s

/-- Emit LLVM IR for networking builtin functions. -/
def genNetworkBuiltins (s : CodegenState) : CodegenState :=
  -- tcp_connect(host: &String, port: Int) -> Int
  -- Uses getaddrinfo for DNS resolution, then connects
  let s := s.emit "@.port_fmt = private constant [5 x i8] c\"%lld\\00\""
  let s := s.emit "define i64 @tcp_connect(ptr %host, i64 %port) {"
  -- Extract C-string from host String
  let s := s.emit "  %h_data_ptr = getelementptr inbounds %struct.String, ptr %host, i32 0, i32 0"
  let s := s.emit "  %h_data = load ptr, ptr %h_data_ptr"
  let s := s.emit "  %h_len_ptr = getelementptr inbounds %struct.String, ptr %host, i32 0, i32 1"
  let s := s.emit "  %h_len = load i64, ptr %h_len_ptr"
  let s := s.emit "  %h_clen = add i64 %h_len, 1"
  let s := s.emit "  %h_cstr = call ptr @malloc(i64 %h_clen)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %h_cstr, ptr %h_data, i64 %h_len, i1 false)"
  let s := s.emit "  %h_null = getelementptr i8, ptr %h_cstr, i64 %h_len"
  let s := s.emit "  store i8 0, ptr %h_null"
  -- Convert port to C-string
  let s := s.emit "  %port_buf = alloca [16 x i8]"
  let s := s.emit "  %port_fmt = getelementptr [5 x i8], ptr @.port_fmt, i64 0, i64 0"
  let s := s.emit "  %port_written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %port_buf, i64 16, ptr %port_fmt, i64 %port)"
  -- Setup hints for getaddrinfo: AF_INET=2, SOCK_STREAM=1
  let s := s.emit "  %hints = alloca [48 x i8]"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %hints, ptr %hints, i64 0, i1 false)"
  -- zero out hints
  let s := s.emit "  %h_i0 = getelementptr i8, ptr %hints, i64 0"
  let s := s.emit "  store i64 0, ptr %h_i0"
  let s := s.emit "  %h_i8 = getelementptr i8, ptr %hints, i64 8"
  let s := s.emit "  store i64 0, ptr %h_i8"
  let s := s.emit "  %h_i16 = getelementptr i8, ptr %hints, i64 16"
  let s := s.emit "  store i64 0, ptr %h_i16"
  let s := s.emit "  %h_i24 = getelementptr i8, ptr %hints, i64 24"
  let s := s.emit "  store i64 0, ptr %h_i24"
  let s := s.emit "  %h_i32 = getelementptr i8, ptr %hints, i64 32"
  let s := s.emit "  store i64 0, ptr %h_i32"
  let s := s.emit "  %h_i40 = getelementptr i8, ptr %hints, i64 40"
  let s := s.emit "  store i64 0, ptr %h_i40"
  -- ai_family = AF_INET (2) at offset 4, ai_socktype = SOCK_STREAM (1) at offset 8
  let s := s.emit "  %hint_family = getelementptr i8, ptr %hints, i64 4"
  let s := s.emit "  store i32 2, ptr %hint_family"
  let s := s.emit "  %hint_socktype = getelementptr i8, ptr %hints, i64 8"
  let s := s.emit "  store i32 1, ptr %hint_socktype"
  -- Call getaddrinfo
  let s := s.emit "  %res_ptr = alloca ptr"
  let s := s.emit "  %gai_ret = call i32 @getaddrinfo(ptr %h_cstr, ptr %port_buf, ptr %hints, ptr %res_ptr)"
  let s := s.emit "  call void @free(ptr %h_cstr)"
  let s := s.emit "  %gai_fail = icmp ne i32 %gai_ret, 0"
  let s := s.emit "  br i1 %gai_fail, label %tc_err, label %tc_ok"
  let s := s.emit "tc_err:"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "tc_ok:"
  let s := s.emit "  %res = load ptr, ptr %res_ptr"
  -- res->ai_family at offset 4 (i32), res->ai_socktype at offset 8 (i32), res->ai_protocol at offset 12 (i32)
  -- res->ai_addrlen at offset 16 (i32), res->ai_addr at offset 32 (ptr on macOS 64-bit)
  let s := s.emit "  %ai_family = getelementptr i8, ptr %res, i64 4"
  let s := s.emit "  %fam = load i32, ptr %ai_family"
  let s := s.emit "  %ai_socktype = getelementptr i8, ptr %res, i64 8"
  let s := s.emit "  %styp = load i32, ptr %ai_socktype"
  let s := s.emit "  %ai_protocol = getelementptr i8, ptr %res, i64 12"
  let s := s.emit "  %proto = load i32, ptr %ai_protocol"
  let s := s.emit "  %sockfd = call i32 @socket(i32 %fam, i32 %styp, i32 %proto)"
  let s := s.emit "  %ai_addrlen = getelementptr i8, ptr %res, i64 16"
  let s := s.emit "  %addrlen = load i32, ptr %ai_addrlen"
  let s := s.emit "  %ai_addr = getelementptr i8, ptr %res, i64 32"
  let s := s.emit "  %addr = load ptr, ptr %ai_addr"
  let s := s.emit "  %conn_ret = call i32 @connect(i32 %sockfd, ptr %addr, i32 %addrlen)"
  let s := s.emit "  call void @freeaddrinfo(ptr %res)"
  let s := s.emit "  %conn_fail = icmp slt i32 %conn_ret, 0"
  let s := s.emit "  br i1 %conn_fail, label %tc_conn_err, label %tc_conn_ok"
  let s := s.emit "tc_conn_err:"
  let s := s.emit "  %sockfd_close = call i32 @close(i32 %sockfd)"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "tc_conn_ok:"
  let s := s.emit "  %sockfd64 = sext i32 %sockfd to i64"
  let s := s.emit "  ret i64 %sockfd64"
  let s := s.emit "}"
  let s := s.emit ""
  -- tcp_listen(port: Int, backlog: Int) -> Int
  let s := s.emit "define i64 @tcp_listen(i64 %port, i64 %backlog) {"
  -- socket(AF_INET=2, SOCK_STREAM=1, 0)
  let s := s.emit "  %lsock = call i32 @socket(i32 2, i32 1, i32 0)"
  -- setsockopt SO_REUSEADDR: SOL_SOCKET=0xFFFF, SO_REUSEADDR=4 on macOS
  let s := s.emit "  %reuse = alloca i32"
  let s := s.emit "  store i32 1, ptr %reuse"
  let s := s.emit "  %sso_ret = call i32 @setsockopt(i32 %lsock, i32 65535, i32 4, ptr %reuse, i32 4)"
  -- Build sockaddr_in on stack (macOS: 16 bytes)
  -- { u8 sin_len=16, u8 sin_family=2, u16 sin_port, u32 sin_addr=0, u8[8] zero }
  let s := s.emit "  %saddr = alloca [16 x i8]"
  -- Zero it out
  let s := s.emit "  %sa0 = getelementptr i8, ptr %saddr, i64 0"
  let s := s.emit "  store i64 0, ptr %sa0"
  let s := s.emit "  %sa8 = getelementptr i8, ptr %saddr, i64 8"
  let s := s.emit "  store i64 0, ptr %sa8"
  -- sin_len = 16
  let s := s.emit "  store i8 16, ptr %saddr"
  -- sin_family = AF_INET (2)
  let s := s.emit "  %sf = getelementptr i8, ptr %saddr, i64 1"
  let s := s.emit "  store i8 2, ptr %sf"
  -- sin_port = htons(port)
  let s := s.emit "  %port16 = trunc i64 %port to i16"
  let s := s.emit "  %port_n = call i16 @htons(i16 %port16)"
  let s := s.emit "  %sp = getelementptr i8, ptr %saddr, i64 2"
  let s := s.emit "  store i16 %port_n, ptr %sp"
  -- sin_addr = INADDR_ANY (0) — already zeroed
  -- bind
  let s := s.emit "  %bind_ret = call i32 @bind(i32 %lsock, ptr %saddr, i32 16)"
  let s := s.emit "  %bind_fail = icmp slt i32 %bind_ret, 0"
  let s := s.emit "  br i1 %bind_fail, label %tl_err, label %tl_listen"
  let s := s.emit "tl_err:"
  let s := s.emit "  %cl_ret = call i32 @close(i32 %lsock)"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "tl_listen:"
  let s := s.emit "  %backlog32 = trunc i64 %backlog to i32"
  let s := s.emit "  %listen_ret = call i32 @listen(i32 %lsock, i32 %backlog32)"
  let s := s.emit "  %listen_fail = icmp slt i32 %listen_ret, 0"
  let s := s.emit "  br i1 %listen_fail, label %tl_err2, label %tl_ok"
  let s := s.emit "tl_err2:"
  let s := s.emit "  %cl2 = call i32 @close(i32 %lsock)"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "tl_ok:"
  let s := s.emit "  %lsock64 = sext i32 %lsock to i64"
  let s := s.emit "  ret i64 %lsock64"
  let s := s.emit "}"
  let s := s.emit ""
  -- tcp_accept(sockfd: Int) -> Int
  let s := s.emit "define i64 @tcp_accept(i64 %sockfd) {"
  let s := s.emit "  %fd32 = trunc i64 %sockfd to i32"
  let s := s.emit "  %newfd = call i32 @accept(i32 %fd32, ptr null, ptr null)"
  let s := s.emit "  %newfd64 = sext i32 %newfd to i64"
  let s := s.emit "  ret i64 %newfd64"
  let s := s.emit "}"
  let s := s.emit ""
  -- socket_send(sockfd: Int, data: &String) -> Int
  let s := s.emit "define i64 @socket_send(i64 %sockfd, ptr %data) {"
  let s := s.emit "  %fd32s = trunc i64 %sockfd to i32"
  let s := s.emit "  %sd_ptr = getelementptr inbounds %struct.String, ptr %data, i32 0, i32 0"
  let s := s.emit "  %sd_data = load ptr, ptr %sd_ptr"
  let s := s.emit "  %sl_ptr = getelementptr inbounds %struct.String, ptr %data, i32 0, i32 1"
  let s := s.emit "  %sd_len = load i64, ptr %sl_ptr"
  let s := s.emit "  %sent = call i64 @send(i32 %fd32s, ptr %sd_data, i64 %sd_len, i32 0)"
  let s := s.emit "  ret i64 %sent"
  let s := s.emit "}"
  let s := s.emit ""
  -- socket_recv(sockfd: Int, bufsize: Int) -> String
  let s := s.emit "define %struct.String @socket_recv(i64 %sockfd, i64 %bufsize) {"
  let s := s.emit "  %fd32r = trunc i64 %sockfd to i32"
  let s := s.emit "  %rbuf = call ptr @malloc(i64 %bufsize)"
  let s := s.emit "  %recvd = call i64 @recv(i32 %fd32r, ptr %rbuf, i64 %bufsize, i32 0)"
  let s := s.emit "  %recv_fail = icmp sle i64 %recvd, 0"
  let s := s.emit "  br i1 %recv_fail, label %sr_empty, label %sr_ok"
  let s := s.emit "sr_empty:"
  let s := s.emit "  call void @free(ptr %rbuf)"
  let s := s.emit "  %empty_buf = call ptr @malloc(i64 1)"
  let s := s.emit "  %sr_e = alloca %struct.String"
  let s := s.emit "  %sr_ed = getelementptr inbounds %struct.String, ptr %sr_e, i32 0, i32 0"
  let s := s.emit "  store ptr %empty_buf, ptr %sr_ed"
  let s := s.emit "  %sr_el = getelementptr inbounds %struct.String, ptr %sr_e, i32 0, i32 1"
  let s := s.emit "  store i64 0, ptr %sr_el"
  let s := s.emit "  %sr_er = load %struct.String, ptr %sr_e"
  let s := s.emit "  ret %struct.String %sr_er"
  let s := s.emit "sr_ok:"
  let s := s.emit "  %sr_a = alloca %struct.String"
  let s := s.emit "  %sr_ad = getelementptr inbounds %struct.String, ptr %sr_a, i32 0, i32 0"
  let s := s.emit "  store ptr %rbuf, ptr %sr_ad"
  let s := s.emit "  %sr_al = getelementptr inbounds %struct.String, ptr %sr_a, i32 0, i32 1"
  let s := s.emit "  store i64 %recvd, ptr %sr_al"
  let s := s.emit "  %sr_ar = load %struct.String, ptr %sr_a"
  let s := s.emit "  ret %struct.String %sr_ar"
  let s := s.emit "}"
  let s := s.emit ""
  -- socket_close(sockfd: Int) -> ()
  let s := s.emit "define void @socket_close(i64 %sockfd) {"
  let s := s.emit "  %fd32c = trunc i64 %sockfd to i32"
  let s := s.emit "  %cl_ret2 = call i32 @close(i32 %fd32c)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  s

end Concrete
