import Concrete.Codegen.Helpers

namespace Concrete

/-- Emit LLVM IR for all built-in standard library functions. -/
def genBuiltinFunctions (s : CodegenState) : CodegenState :=
  -- Built-in string functions
  let s := s.emit "define i64 @string_length(ptr %s) {"
  let s := s.emit "  %len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len = load i64, ptr %len_ptr"
  let s := s.emit "  ret i64 %len"
  let s := s.emit "}"
  let s := s.emit ""
  let s := s.emit "define void @drop_string(ptr %s) {"
  let s := s.emit "  %data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data = load ptr, ptr %data_ptr"
  let s := s.emit "  call void @free(ptr %data)"
  let s := s.emit "  ret void"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_concat: takes two Strings by value, returns a new String
  let s := s.emit "define %struct.String @string_concat(ptr %a, ptr %b) {"
  let s := s.emit "  %a_data_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 0"
  let s := s.emit "  %a_data = load ptr, ptr %a_data_ptr"
  let s := s.emit "  %a_len_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 1"
  let s := s.emit "  %a_len = load i64, ptr %a_len_ptr"
  let s := s.emit "  %b_data_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 0"
  let s := s.emit "  %b_data = load ptr, ptr %b_data_ptr"
  let s := s.emit "  %b_len_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 1"
  let s := s.emit "  %b_len = load i64, ptr %b_len_ptr"
  let s := s.emit "  %total_len = add i64 %a_len, %b_len"
  let s := s.emit "  %buf = call ptr @malloc(i64 %total_len)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %a_data, i64 %a_len, i1 false)"
  let s := s.emit "  %dst = getelementptr i8, ptr %buf, i64 %a_len"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %dst, ptr %b_data, i64 %b_len, i1 false)"
  let s := s.emit "  ; Free the input strings"
  let s := s.emit "  call void @free(ptr %a_data)"
  let s := s.emit "  call void @free(ptr %b_data)"
  let s := s.emit "  %sc_alloca = alloca %struct.String"
  let s := s.emit "  %sc_data_ptr = getelementptr inbounds %struct.String, ptr %sc_alloca, i32 0, i32 0"
  let s := s.emit "  store ptr %buf, ptr %sc_data_ptr"
  let s := s.emit "  %sc_len_ptr = getelementptr inbounds %struct.String, ptr %sc_alloca, i32 0, i32 1"
  let s := s.emit "  store i64 %total_len, ptr %sc_len_ptr"
  let s := s.emit "  %sc_cap_ptr = getelementptr inbounds %struct.String, ptr %sc_alloca, i32 0, i32 2"
  let s := s.emit "  store i64 %total_len, ptr %sc_cap_ptr"
  let s := s.emit "  %sc_result = load %struct.String, ptr %sc_alloca"
  let s := s.emit "  ret %struct.String %sc_result"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_slice
  let s := s.emit "define %struct.String @string_slice(ptr %s, i64 %start, i64 %end_) {"
  let s := s.emit "  %len_ptr.ss = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len.ss = load i64, ptr %len_ptr.ss"
  let s := s.emit "  %s_clamped = call i64 @llvm.smax.i64(i64 %start, i64 0)"
  let s := s.emit "  %s_min = call i64 @llvm.smin.i64(i64 %s_clamped, i64 %len.ss)"
  let s := s.emit "  %e_clamped = call i64 @llvm.smax.i64(i64 %end_, i64 0)"
  let s := s.emit "  %e_min = call i64 @llvm.smin.i64(i64 %e_clamped, i64 %len.ss)"
  let s := s.emit "  %e_final = call i64 @llvm.smax.i64(i64 %e_min, i64 %s_min)"
  let s := s.emit "  %slice_len = sub i64 %e_final, %s_min"
  let s := s.emit "  %slice_buf = call ptr @malloc(i64 %slice_len)"
  let s := s.emit "  %data_ptr.ss = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data.ss = load ptr, ptr %data_ptr.ss"
  let s := s.emit "  %src = getelementptr i8, ptr %data.ss, i64 %s_min"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %slice_buf, ptr %src, i64 %slice_len, i1 false)"
  let s := s.emit "  %res.ss = alloca %struct.String"
  let s := s.emit "  %res_d.ss = getelementptr inbounds %struct.String, ptr %res.ss, i32 0, i32 0"
  let s := s.emit "  store ptr %slice_buf, ptr %res_d.ss"
  let s := s.emit "  %res_l.ss = getelementptr inbounds %struct.String, ptr %res.ss, i32 0, i32 1"
  let s := s.emit "  store i64 %slice_len, ptr %res_l.ss"
  let s := s.emit "  %res_c.ss = getelementptr inbounds %struct.String, ptr %res.ss, i32 0, i32 2"
  let s := s.emit "  store i64 %slice_len, ptr %res_c.ss"
  let s := s.emit "  %result.ss = load %struct.String, ptr %res.ss"
  let s := s.emit "  ret %struct.String %result.ss"
  let s := s.emit "}"
  let s := s.emit "declare i64 @llvm.smax.i64(i64, i64)"
  let s := s.emit "declare i64 @llvm.smin.i64(i64, i64)"
  let s := s.emit ""
  -- string_char_at
  let s := s.emit "define i64 @string_char_at(ptr %s, i64 %index) {"
  let s := s.emit "  %len_ptr.sca = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %len.sca = load i64, ptr %len_ptr.sca"
  let s := s.emit "  %neg = icmp slt i64 %index, 0"
  let s := s.emit "  %oob = icmp sge i64 %index, %len.sca"
  let s := s.emit "  %bad = or i1 %neg, %oob"
  let s := s.emit "  br i1 %bad, label %ret_neg, label %ok_idx"
  let s := s.emit "ret_neg:"
  let s := s.emit "  ret i64 -1"
  let s := s.emit "ok_idx:"
  let s := s.emit "  %data_ptr.sca = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %data.sca = load ptr, ptr %data_ptr.sca"
  let s := s.emit "  %char_ptr = getelementptr i8, ptr %data.sca, i64 %index"
  let s := s.emit "  %byte = load i8, ptr %char_ptr"
  let s := s.emit "  %char = zext i8 %byte to i64"
  let s := s.emit "  ret i64 %char"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_contains
  let s := s.emit "define i1 @string_contains(ptr %haystack, ptr %needle) {"
  let s := s.emit "  %h_data_ptr = getelementptr inbounds %struct.String, ptr %haystack, i32 0, i32 0"
  let s := s.emit "  %h_data = load ptr, ptr %h_data_ptr"
  let s := s.emit "  %h_len_ptr = getelementptr inbounds %struct.String, ptr %haystack, i32 0, i32 1"
  let s := s.emit "  %h_len = load i64, ptr %h_len_ptr"
  let s := s.emit "  %n_data_ptr = getelementptr inbounds %struct.String, ptr %needle, i32 0, i32 0"
  let s := s.emit "  %n_data = load ptr, ptr %n_data_ptr"
  let s := s.emit "  %n_len_ptr = getelementptr inbounds %struct.String, ptr %needle, i32 0, i32 1"
  let s := s.emit "  %n_len = load i64, ptr %n_len_ptr"
  let s := s.emit "  %n_empty = icmp eq i64 %n_len, 0"
  let s := s.emit "  br i1 %n_empty, label %found, label %check_len"
  let s := s.emit "check_len:"
  let s := s.emit "  %too_long = icmp ugt i64 %n_len, %h_len"
  let s := s.emit "  br i1 %too_long, label %not_found, label %loop_start"
  let s := s.emit "loop_start:"
  let s := s.emit "  %max_i = sub i64 %h_len, %n_len"
  let s := s.emit "  br label %loop"
  let s := s.emit "loop:"
  let s := s.emit "  %i = phi i64 [0, %loop_start], [%i_next, %loop_cont]"
  let s := s.emit "  %h_ptr = getelementptr i8, ptr %h_data, i64 %i"
  let s := s.emit "  %cmp = call i32 @memcmp(ptr %h_ptr, ptr %n_data, i64 %n_len)"
  let s := s.emit "  %match = icmp eq i32 %cmp, 0"
  let s := s.emit "  br i1 %match, label %found, label %loop_cont"
  let s := s.emit "loop_cont:"
  let s := s.emit "  %i_next = add i64 %i, 1"
  let s := s.emit "  %done = icmp ugt i64 %i_next, %max_i"
  let s := s.emit "  br i1 %done, label %not_found, label %loop"
  let s := s.emit "found:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "not_found:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_eq
  let s := s.emit "define i1 @string_eq(ptr %a, ptr %b) {"
  let s := s.emit "  %a_len_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 1"
  let s := s.emit "  %a_len = load i64, ptr %a_len_ptr"
  let s := s.emit "  %b_len_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 1"
  let s := s.emit "  %b_len = load i64, ptr %b_len_ptr"
  let s := s.emit "  %len_eq = icmp eq i64 %a_len, %b_len"
  let s := s.emit "  br i1 %len_eq, label %cmp_data, label %not_eq"
  let s := s.emit "cmp_data:"
  let s := s.emit "  %zero_len = icmp eq i64 %a_len, 0"
  let s := s.emit "  br i1 %zero_len, label %eq, label %do_cmp"
  let s := s.emit "do_cmp:"
  let s := s.emit "  %a_data_ptr = getelementptr inbounds %struct.String, ptr %a, i32 0, i32 0"
  let s := s.emit "  %a_data = load ptr, ptr %a_data_ptr"
  let s := s.emit "  %b_data_ptr = getelementptr inbounds %struct.String, ptr %b, i32 0, i32 0"
  let s := s.emit "  %b_data = load ptr, ptr %b_data_ptr"
  let s := s.emit "  %cmp_res = call i32 @memcmp(ptr %a_data, ptr %b_data, i64 %a_len)"
  let s := s.emit "  %eq_data = icmp eq i32 %cmp_res, 0"
  let s := s.emit "  br i1 %eq_data, label %eq, label %not_eq"
  let s := s.emit "eq:"
  let s := s.emit "  ret i1 true"
  let s := s.emit "not_eq:"
  let s := s.emit "  ret i1 false"
  let s := s.emit "}"
  let s := s.emit ""
  s

/-- Emit LLVM IR for conversion and I/O builtins. -/
def genConversionBuiltins (s : CodegenState) : CodegenState :=
  -- int_to_string
  let s := s.emit "@.fmt_ld = private constant [4 x i8] c\"%ld\\00\""
  let s := s.emit "define %struct.String @int_to_string(i64 %n) {"
  let s := s.emit "  %buf = call ptr @malloc(i64 32)"
  let s := s.emit "  %fmt_its = getelementptr [4 x i8], ptr @.fmt_ld, i64 0, i64 0"
  let s := s.emit "  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buf, i64 32, ptr %fmt_its, i64 %n)"
  let s := s.emit "  %wext = sext i32 %written to i64"
  let s := s.emit "  %res.its = alloca %struct.String"
  let s := s.emit "  %res_d.its = getelementptr inbounds %struct.String, ptr %res.its, i32 0, i32 0"
  let s := s.emit "  store ptr %buf, ptr %res_d.its"
  let s := s.emit "  %res_l.its = getelementptr inbounds %struct.String, ptr %res.its, i32 0, i32 1"
  let s := s.emit "  store i64 %wext, ptr %res_l.its"
  let s := s.emit "  %res_c.its = getelementptr inbounds %struct.String, ptr %res.its, i32 0, i32 2"
  let s := s.emit "  store i64 32, ptr %res_c.its"
  let s := s.emit "  %result.its = load %struct.String, ptr %res.its"
  let s := s.emit "  ret %struct.String %result.its"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_to_int — returns Result<Int, Int>
  let s := s.emit "define %enum.Result @string_to_int(ptr %s) {"
  let s := s.emit "  %sti_data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %sti_data = load ptr, ptr %sti_data_ptr"
  let s := s.emit "  %sti_len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %sti_len = load i64, ptr %sti_len_ptr"
  let s := s.emit "  %sti_buf_sz = add i64 %sti_len, 1"
  let s := s.emit "  %sti_buf = call ptr @malloc(i64 %sti_buf_sz)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %sti_buf, ptr %sti_data, i64 %sti_len, i1 false)"
  let s := s.emit "  %sti_null = getelementptr i8, ptr %sti_buf, i64 %sti_len"
  let s := s.emit "  store i8 0, ptr %sti_null"
  let s := s.emit "  %endptr_alloca = alloca ptr"
  let s := s.emit "  %sti_val = call i64 @strtol(ptr %sti_buf, ptr %endptr_alloca, i32 10)"
  let s := s.emit "  %endptr = load ptr, ptr %endptr_alloca"
  let s := s.emit "  %end_expected = getelementptr i8, ptr %sti_buf, i64 %sti_len"
  let s := s.emit "  %valid = icmp eq ptr %endptr, %end_expected"
  let s := s.emit "  %empty_input = icmp eq i64 %sti_len, 0"
  let s := s.emit "  %not_empty = xor i1 %empty_input, true"
  let s := s.emit "  %final_ok = and i1 %valid, %not_empty"
  let s := s.emit "  call void @free(ptr %sti_buf)"
  let s := s.emit "  %res.sti = alloca %enum.Result"
  let s := s.emit "  br i1 %final_ok, label %sti_ok, label %sti_err"
  let s := s.emit "sti_ok:"
  let s := s.emit "  store i32 0, ptr %res.sti"
  let s := s.emit "  %data_ptr.sti_ok = getelementptr i8, ptr %res.sti, i64 8"
  let s := s.emit "  store i64 %sti_val, ptr %data_ptr.sti_ok"
  let s := s.emit "  br label %sti_done"
  let s := s.emit "sti_err:"
  let s := s.emit "  store i32 1, ptr %res.sti"
  let s := s.emit "  %data_ptr.sti_err = getelementptr i8, ptr %res.sti, i64 8"
  let s := s.emit "  store i64 1, ptr %data_ptr.sti_err"
  let s := s.emit "  br label %sti_done"
  let s := s.emit "sti_done:"
  let s := s.emit "  %result.sti = load %enum.Result, ptr %res.sti"
  let s := s.emit "  ret %enum.Result %result.sti"
  let s := s.emit "}"
  let s := s.emit ""
  -- bool_to_string
  let s := s.emit "@.str_true = private constant [4 x i8] c\"true\""
  let s := s.emit "@.str_false = private constant [5 x i8] c\"false\""
  let s := s.emit "define %struct.String @bool_to_string(i1 %b) {"
  let s := s.emit "  br i1 %b, label %bts_true, label %bts_false"
  let s := s.emit "bts_true:"
  let s := s.emit "  %tbuf = call ptr @malloc(i64 4)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %tbuf, ptr @.str_true, i64 4, i1 false)"
  let s := s.emit "  %tres = alloca %struct.String"
  let s := s.emit "  %td = getelementptr inbounds %struct.String, ptr %tres, i32 0, i32 0"
  let s := s.emit "  store ptr %tbuf, ptr %td"
  let s := s.emit "  %tl = getelementptr inbounds %struct.String, ptr %tres, i32 0, i32 1"
  let s := s.emit "  store i64 4, ptr %tl"
  let s := s.emit "  %tc = getelementptr inbounds %struct.String, ptr %tres, i32 0, i32 2"
  let s := s.emit "  store i64 4, ptr %tc"
  let s := s.emit "  %tresult = load %struct.String, ptr %tres"
  let s := s.emit "  ret %struct.String %tresult"
  let s := s.emit "bts_false:"
  let s := s.emit "  %fbuf = call ptr @malloc(i64 5)"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %fbuf, ptr @.str_false, i64 5, i1 false)"
  let s := s.emit "  %fres = alloca %struct.String"
  let s := s.emit "  %fd = getelementptr inbounds %struct.String, ptr %fres, i32 0, i32 0"
  let s := s.emit "  store ptr %fbuf, ptr %fd"
  let s := s.emit "  %fl = getelementptr inbounds %struct.String, ptr %fres, i32 0, i32 1"
  let s := s.emit "  store i64 5, ptr %fl"
  let s := s.emit "  %fc = getelementptr inbounds %struct.String, ptr %fres, i32 0, i32 2"
  let s := s.emit "  store i64 5, ptr %fc"
  let s := s.emit "  %fresult = load %struct.String, ptr %fres"
  let s := s.emit "  ret %struct.String %fresult"
  let s := s.emit "}"
  let s := s.emit ""
  -- float_to_string
  let s := s.emit "@.fmt_f = private constant [3 x i8] c\"%g\\00\""
  let s := s.emit "define %struct.String @float_to_string(double %f) {"
  let s := s.emit "  %fbuf.fts = call ptr @malloc(i64 64)"
  let s := s.emit "  %fmt.fts = getelementptr [3 x i8], ptr @.fmt_f, i64 0, i64 0"
  let s := s.emit "  %written.fts = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %fbuf.fts, i64 64, ptr %fmt.fts, double %f)"
  let s := s.emit "  %wext.fts = sext i32 %written.fts to i64"
  let s := s.emit "  %res.fts = alloca %struct.String"
  let s := s.emit "  %res_d.fts = getelementptr inbounds %struct.String, ptr %res.fts, i32 0, i32 0"
  let s := s.emit "  store ptr %fbuf.fts, ptr %res_d.fts"
  let s := s.emit "  %res_l.fts = getelementptr inbounds %struct.String, ptr %res.fts, i32 0, i32 1"
  let s := s.emit "  store i64 %wext.fts, ptr %res_l.fts"
  let s := s.emit "  %res_c.fts = getelementptr inbounds %struct.String, ptr %res.fts, i32 0, i32 2"
  let s := s.emit "  store i64 64, ptr %res_c.fts"
  let s := s.emit "  %result.fts = load %struct.String, ptr %res.fts"
  let s := s.emit "  ret %struct.String %result.fts"
  let s := s.emit "}"
  let s := s.emit ""
  -- string_trim
  let s := s.emit "define %struct.String @string_trim(ptr %s) {"
  let s := s.emit "  %st_data_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 0"
  let s := s.emit "  %st_data = load ptr, ptr %st_data_ptr"
  let s := s.emit "  %st_len_ptr = getelementptr inbounds %struct.String, ptr %s, i32 0, i32 1"
  let s := s.emit "  %st_len = load i64, ptr %st_len_ptr"
  let s := s.emit "  br label %trim_left"
  let s := s.emit "trim_left:"
  let s := s.emit "  %tl_i = phi i64 [0, %0], [%tl_next, %tl_ws]"
  let s := s.emit "  %tl_done = icmp uge i64 %tl_i, %st_len"
  let s := s.emit "  br i1 %tl_done, label %trim_result, label %tl_check"
  let s := s.emit "tl_check:"
  let s := s.emit "  %tl_ptr = getelementptr i8, ptr %st_data, i64 %tl_i"
  let s := s.emit "  %tl_ch = load i8, ptr %tl_ptr"
  let s := s.emit "  %tl_is_sp = icmp eq i8 %tl_ch, 32"
  let s := s.emit "  %tl_is_tab = icmp eq i8 %tl_ch, 9"
  let s := s.emit "  %tl_is_nl = icmp eq i8 %tl_ch, 10"
  let s := s.emit "  %tl_is_cr = icmp eq i8 %tl_ch, 13"
  let s := s.emit "  %tl_w1 = or i1 %tl_is_sp, %tl_is_tab"
  let s := s.emit "  %tl_w2 = or i1 %tl_is_nl, %tl_is_cr"
  let s := s.emit "  %tl_is_ws = or i1 %tl_w1, %tl_w2"
  let s := s.emit "  br i1 %tl_is_ws, label %tl_ws, label %trim_right_init"
  let s := s.emit "tl_ws:"
  let s := s.emit "  %tl_next = add i64 %tl_i, 1"
  let s := s.emit "  br label %trim_left"
  let s := s.emit "trim_right_init:"
  let s := s.emit "  %tr_start = sub i64 %st_len, 1"
  let s := s.emit "  br label %trim_right"
  let s := s.emit "trim_right:"
  let s := s.emit "  %tr_i = phi i64 [%tr_start, %trim_right_init], [%tr_prev, %tr_ws]"
  let s := s.emit "  %tr_done = icmp ult i64 %tr_i, %tl_i"
  let s := s.emit "  br i1 %tr_done, label %trim_result, label %tr_check"
  let s := s.emit "tr_check:"
  let s := s.emit "  %tr_ptr = getelementptr i8, ptr %st_data, i64 %tr_i"
  let s := s.emit "  %tr_ch = load i8, ptr %tr_ptr"
  let s := s.emit "  %tr_is_sp = icmp eq i8 %tr_ch, 32"
  let s := s.emit "  %tr_is_tab = icmp eq i8 %tr_ch, 9"
  let s := s.emit "  %tr_is_nl = icmp eq i8 %tr_ch, 10"
  let s := s.emit "  %tr_is_cr = icmp eq i8 %tr_ch, 13"
  let s := s.emit "  %tr_w1 = or i1 %tr_is_sp, %tr_is_tab"
  let s := s.emit "  %tr_w2 = or i1 %tr_is_nl, %tr_is_cr"
  let s := s.emit "  %tr_is_ws = or i1 %tr_w1, %tr_w2"
  let s := s.emit "  br i1 %tr_is_ws, label %tr_ws, label %trim_result"
  let s := s.emit "tr_ws:"
  let s := s.emit "  %tr_prev = sub i64 %tr_i, 1"
  let s := s.emit "  br label %trim_right"
  let s := s.emit "trim_result:"
  let s := s.emit "  %tr_left = phi i64 [%tl_i, %trim_left], [%tl_i, %trim_right], [%tl_i, %tr_check]"
  let s := s.emit "  %tr_right_raw = phi i64 [0, %trim_left], [%tl_i, %trim_right], [%tr_i, %tr_check]"
  let s := s.emit "  %tr_right = add i64 %tr_right_raw, 1"
  let s := s.emit "  %tr_empty = icmp uge i64 %tr_left, %tr_right"
  let s := s.emit "  br i1 %tr_empty, label %trim_empty, label %trim_copy"
  let s := s.emit "trim_empty:"
  let s := s.emit "  %te_buf = call ptr @malloc(i64 1)"
  let s := s.emit "  %te_res = alloca %struct.String"
  let s := s.emit "  %te_d = getelementptr inbounds %struct.String, ptr %te_res, i32 0, i32 0"
  let s := s.emit "  store ptr %te_buf, ptr %te_d"
  let s := s.emit "  %te_l = getelementptr inbounds %struct.String, ptr %te_res, i32 0, i32 1"
  let s := s.emit "  store i64 0, ptr %te_l"
  let s := s.emit "  %te_c = getelementptr inbounds %struct.String, ptr %te_res, i32 0, i32 2"
  let s := s.emit "  store i64 1, ptr %te_c"
  let s := s.emit "  %te_result = load %struct.String, ptr %te_res"
  let s := s.emit "  ret %struct.String %te_result"
  let s := s.emit "trim_copy:"
  let s := s.emit "  %tc_len = sub i64 %tr_right, %tr_left"
  let s := s.emit "  %tc_buf = call ptr @malloc(i64 %tc_len)"
  let s := s.emit "  %tc_src = getelementptr i8, ptr %st_data, i64 %tr_left"
  let s := s.emit "  call void @llvm.memcpy.p0.p0.i64(ptr %tc_buf, ptr %tc_src, i64 %tc_len, i1 false)"
  let s := s.emit "  %tc_res = alloca %struct.String"
  let s := s.emit "  %tc_d = getelementptr inbounds %struct.String, ptr %tc_res, i32 0, i32 0"
  let s := s.emit "  store ptr %tc_buf, ptr %tc_d"
  let s := s.emit "  %tc_l = getelementptr inbounds %struct.String, ptr %tc_res, i32 0, i32 1"
  let s := s.emit "  store i64 %tc_len, ptr %tc_l"
  let s := s.emit "  %tc_c = getelementptr inbounds %struct.String, ptr %tc_res, i32 0, i32 2"
  let s := s.emit "  store i64 %tc_len, ptr %tc_c"
  let s := s.emit "  %tc_result = load %struct.String, ptr %tc_res"
  let s := s.emit "  ret %struct.String %tc_result"
  let s := s.emit "}"
  let s := s.emit ""
  s

-- HashMap builtin functions removed: HashMap is now a stdlib type compiled
-- natively through the normal generic struct path (no builtin interception).

end Concrete
