import Concrete.Codegen.Builtins

namespace Concrete

def genModule (m : Module) : String :=
  -- Add built-in Option<T> enum if not user-defined
  let builtinOptionEnum : EnumDef := {
    name := "Option"
    typeParams := ["T"]
    variants := [
      { name := "Some", fields := [{ name := "value", ty := .typeVar "T" }] },
      { name := "None", fields := [] }
    ]
  }
  let builtinResultEnum : EnumDef := {
    name := "Result"
    typeParams := ["T", "E"]
    variants := [
      { name := "Ok", fields := [{ name := "value", ty := .typeVar "T" }] },
      { name := "Err", fields := [{ name := "value", ty := .typeVar "E" }] }
    ]
  }
  let hasUserOption := m.enums.any fun ed => ed.name == "Option"
  let hasUserResult := m.enums.any fun ed => ed.name == "Result"
  let builtinEnums := (if hasUserOption then [] else [builtinOptionEnum]) ++
                      (if hasUserResult then [] else [builtinResultEnum])
  let allEnums := builtinEnums ++ m.enums
  let structInfos := buildStructDefs m.structs
  let enumInfos := buildEnumDefs allEnums
  let builtinRetTypes := [
    ("string_length", Ty.int),
    ("drop_string", Ty.unit),
    ("print_string", Ty.unit),
    ("string_concat", Ty.string),
    ("print_int", Ty.unit),
    ("print_bool", Ty.unit),
    ("read_file", Ty.string),
    ("write_file", Ty.int),
    ("string_slice", Ty.string),
    ("string_char_at", Ty.int),
    ("string_contains", Ty.bool),
    ("string_eq", Ty.bool),
    ("int_to_string", Ty.string),
    ("string_to_int", Ty.generic "Result" [.int, .int]),
    ("bool_to_string", Ty.string),
    ("float_to_string", Ty.string),
    ("read_line", Ty.string),
    ("print_char", Ty.unit),
    ("eprint_string", Ty.unit),
    ("get_env", Ty.generic "Option" [.string]),
    ("get_args", Ty.heapArray .string),
    ("exit_process", Ty.unit),
    ("string_trim", Ty.string),
    ("tcp_connect", Ty.int),
    ("tcp_listen", Ty.int),
    ("tcp_accept", Ty.int),
    ("socket_send", Ty.int),
    ("socket_recv", Ty.string),
    ("socket_close", Ty.unit)
  ]
  let implRetTypes := m.implBlocks.foldl (fun acc ib =>
    acc ++ ib.methods.map fun f => (ib.typeName ++ "_" ++ f.name, f.retTy)
  ) ([] : List (String × Ty))
  let traitImplRetTypes := m.traitImpls.foldl (fun acc tb =>
    acc ++ tb.methods.map fun f => (tb.typeName ++ "_" ++ f.name, f.retTy)
  ) ([] : List (String × Ty))
  let externRetTypes := m.externFns.map fun ef => (ef.name, ef.retTy)
  let fnRetTypes := ((m.functions.map fun f => (f.name, normalizeFieldTy f.retTy)) ++ builtinRetTypes ++ implRetTypes ++ traitImplRetTypes ++ externRetTypes).map fun (n, t) => (n, normalizeFieldTy t)
  let fnParamTypes : List (String × List Ty) := (m.functions.map fun f =>
    (f.name, f.params.map fun p => normalizeFieldTy p.ty)) ++
    (m.implBlocks.foldl (fun acc ib =>
      acc ++ ib.methods.map fun f => (ib.typeName ++ "_" ++ f.name, f.params.map fun p => normalizeFieldTy p.ty)
    ) []) ++
    (m.traitImpls.foldl (fun acc tb =>
      acc ++ tb.methods.map fun f => (tb.typeName ++ "_" ++ f.name, f.params.map fun p => normalizeFieldTy p.ty)
    ) []) ++
    (m.externFns.map fun ef => (ef.name, ef.params.map fun p => normalizeFieldTy p.ty))
  let constList := m.constants.map fun c => (c.name, (c.ty, c.value))
  -- Build type param and type bound maps for monomorphization
  let fnTypeParams : List (String × List String) := m.functions.map fun f => (f.name, f.typeParams)
  let fnTypeBounds : List (String × List (String × List String)) := m.functions.filter (fun f => !f.typeBounds.isEmpty) |>.map fun f => (f.name, f.typeBounds)
  let s0 := { CodegenState.init with
    structDefs := structInfos, enumDefs := enumInfos,
    fnRetTypes := fnRetTypes, fnParamTypes := fnParamTypes,
    constants := constList }
  let s := { s0 with
    fnTypeParams := fnTypeParams,
    fnTypeBounds := fnTypeBounds,
    allFnDefs := m.functions }
  let s := s.emit "; Generated by Concrete compiler"
  let s := s.emit ("; Module: " ++ m.name)
  let s := s.emit ""
  -- Only emit built-in String type if user hasn't defined one
  let hasUserString := m.structs.any fun sd => sd.name == "String"
  let s := if !hasUserString then
    let s := s.emit "%struct.String = type { ptr, i64 }"
    s.emit ""
  else s
  let s := s.emit "%struct.Vec = type { ptr, i64, i64 }"
  let s := s.emit "%struct.HashMap = type { ptr, ptr, ptr, i64, i64 }"
  let s := s.emit ""
  let s := genStructTypes s m.structs
  let s := if m.structs.isEmpty then s else s.emit ""
  let s := genEnumTypes s allEnums
  let s := if allEnums.isEmpty then s else s.emit ""
  -- External declarations
  let s := s.emit "declare ptr @malloc(i64)"
  let s := s.emit "declare void @free(ptr)"
  let s := s.emit "declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)"
  let s := s.emit "declare i64 @write(i32, ptr, i64)"
  let s := s.emit "declare void @abort()"
  let s := s.emit "declare i32 @printf(ptr, ...)"
  -- C file I/O declarations
  let s := s.emit "declare ptr @fopen(ptr, ptr)"
  let s := s.emit "declare i64 @fread(ptr, i64, i64, ptr)"
  let s := s.emit "declare i64 @fwrite(ptr, i64, i64, ptr)"
  let s := s.emit "declare i32 @fclose(ptr)"
  let s := s.emit "declare i32 @fseek(ptr, i64, i32)"
  let s := s.emit "declare i64 @ftell(ptr)"
  -- C stdlib declarations for new builtins
  let s := s.emit "declare i32 @snprintf(ptr, i64, ptr, ...)"
  let s := s.emit "declare i64 @strtol(ptr, ptr, i32)"
  let s := s.emit "declare i32 @memcmp(ptr, ptr, i64)"
  let s := s.emit "declare ptr @getenv(ptr)"
  let s := s.emit "declare i64 @strlen(ptr)"
  let s := s.emit "declare ptr @realloc(ptr, i64)"
  let s := s.emit "declare i64 @read(i32, ptr, i64)"
  let s := s.emit "declare i32 @putchar(i32)"
  let s := s.emit "declare void @exit(i32)"
  -- POSIX socket declarations
  let s := s.emit "declare i32 @socket(i32, i32, i32)"
  let s := s.emit "declare i32 @connect(i32, ptr, i32)"
  let s := s.emit "declare i32 @bind(i32, ptr, i32)"
  let s := s.emit "declare i32 @listen(i32, i32)"
  let s := s.emit "declare i32 @accept(i32, ptr, ptr)"
  let s := s.emit "declare i64 @send(i32, ptr, i64, i32)"
  let s := s.emit "declare i64 @recv(i32, ptr, i64, i32)"
  let s := s.emit "declare i32 @close(i32)"
  let s := s.emit "declare i32 @getaddrinfo(ptr, ptr, ptr, ptr)"
  let s := s.emit "declare void @freeaddrinfo(ptr)"
  let s := s.emit "declare i16 @htons(i16)"
  let s := s.emit "declare i32 @setsockopt(i32, i32, i32, ptr, i32)"
  -- Extern function declarations from the source
  let s := m.externFns.foldl (fun s ef =>
    let retLLTy := tyToLLVM s ef.retTy
    let paramStr := ", ".intercalate (ef.params.map fun p => paramTyToLLVM s p.ty)
    -- Skip if already declared (malloc, free, etc.)
    if ef.name == "malloc" || ef.name == "free" then s
    else s.emit ("declare " ++ retLLTy ++ " @" ++ ef.name ++ "(" ++ paramStr ++ ")")
  ) s
  let s := s.emit ""
  -- Emit all builtin function implementations
  let s := genBuiltinFunctions s
  let s := genConversionBuiltins s
  let s := genNetworkBuiltins s
  let s := genHashMapFunctions s
  -- Impl block methods
  let s := m.implBlocks.foldl (fun s ib =>
    ib.methods.foldl (fun s f =>
      let mangledF : FnDef := { f with name := ib.typeName ++ "_" ++ f.name }
      genFn s mangledF
    ) s
  ) s
  -- Trait impl methods
  let s := m.traitImpls.foldl (fun s tb =>
    tb.methods.foldl (fun s f =>
      let mangledF : FnDef := { f with name := tb.typeName ++ "_" ++ f.name }
      genFn s mangledF
    ) s
  ) s
  -- User functions (skip generic functions with trait bounds — they get monomorphized)
  let hasMain := m.functions.any (fun f => f.name == "main")
  let s := m.functions.foldl (fun s f =>
    if !f.typeBounds.isEmpty then s  -- skip: will be monomorphized at call sites
    else genFn s f hasMain
  ) s
  -- Process monomorphization queue: generate specialized copies of generic functions
  let s := Id.run do
    let mut s := s
    let mut processed : Nat := 0
    -- Iterate until queue is exhausted (mono fns may enqueue more)
    while processed < s.monoQueue.length do
      match s.monoQueue.drop processed with
      | (_, monoFn) :: _ =>
        s := genFn s monoFn
        processed := processed + 1
      | [] => break
    return s
  -- String literal globals
  let s := if s.stringGlobals.isEmpty then s
    else { s with output := s.output ++ s.stringGlobals ++ "\n" }
  if hasMain then
    -- Find main function signature
    let mainFn := m.functions.find? fun f => f.name == "main"
    let mainRetTy := match mainFn with
      | some f => f.retTy
      | none => .int
    let mainRetLLTy := tyToLLVM s mainRetTy
    let mainHasParams := match mainFn with
      | some f => !f.params.isEmpty
      | none => false
    if mainRetLLTy == "void" then
      -- Unit/void return: just call, no print
      let s := s.emit "define i32 @main() {"
      let s := s.emit "  call void @concrete_main()"
      let s := s.emit "  ret i32 0"
      let s := s.emit "}"
      s.output
    else
    let s := s.emit "@.fmt = private constant [5 x i8] c\"%ld\\0A\\00\""
    let s := s.emit ""
    if mainHasParams then
      -- Main with argc: fn main(argc: i64)
      let s := s.emit "define i32 @main(i32 %argc, ptr %argv) {"
      let s := s.emit "  %argc64 = sext i32 %argc to i64"
      let s := s.emit ("  %result = call " ++ mainRetLLTy ++ " @concrete_main(i64 %argc64)")
      -- Widen result to i64 for printf if needed
      let (s, resultI64) := if mainRetLLTy != "i64" then
        let line := "  %result64 = sext " ++ mainRetLLTy ++ " %result to i64"
        (s.emit line, "%result64")
      else
        (s, "%result")
      let s := s.emit "  %fmt = getelementptr [5 x i8], ptr @.fmt, i64 0, i64 0"
      let s := s.emit ("  call i32 (ptr, ...) @printf(ptr %fmt, i64 " ++ resultI64 ++ ")")
      -- Return exit code (truncated to i32)
      let (s, retVal) := if mainRetLLTy == "i32" then
        (s, "%result")
      else if mainRetLLTy == "i64" then
        (s.emit "  %exitcode = trunc i64 %result to i32", "%exitcode")
      else
        (s.emit ("  %exitcode = trunc i64 " ++ resultI64 ++ " to i32"), "%exitcode")
      let s := s.emit ("  ret i32 " ++ retVal)
      let s := s.emit "}"
      s.output
    else
      let s := s.emit "define i32 @main() {"
      let s := s.emit ("  %result = call " ++ mainRetLLTy ++ " @concrete_main()")
      -- Widen result to i64 for printf if needed
      let (s, resultI64) := if mainRetLLTy != "i64" then
        if mainRetLLTy == "i32" then
          (s.emit "  %result64 = sext i32 %result to i64", "%result64")
        else if mainRetLLTy == "i1" then
          (s.emit "  %result64 = zext i1 %result to i64", "%result64")
        else if mainRetLLTy == "i8" then
          (s.emit "  %result64 = zext i8 %result to i64", "%result64")
        else if mainRetLLTy == "i16" then
          (s.emit "  %result64 = sext i16 %result to i64", "%result64")
        else
          (s, "%result")
      else
        (s, "%result")
      let s := s.emit "  %fmt = getelementptr [5 x i8], ptr @.fmt, i64 0, i64 0"
      let s := s.emit ("  call i32 (ptr, ...) @printf(ptr %fmt, i64 " ++ resultI64 ++ ")")
      -- Return exit code
      let (s, retVal) := if mainRetLLTy == "i32" then
        (s, "%result")
      else if mainRetLLTy == "i64" then
        (s.emit "  %exitcode = trunc i64 %result to i32", "%exitcode")
      else
        (s.emit ("  %exitcode.tmp = zext " ++ mainRetLLTy ++ " %result to i32"), "%exitcode.tmp")
      let s := s.emit ("  ret i32 " ++ retVal)
      let s := s.emit "}"
      s.output
  else
    s.output

private def flattenModule (m : Module) : Module :=
  let subStructs := m.submodules.foldl (fun acc sub => acc ++ sub.structs) ([] : List StructDef)
  let subEnums := m.submodules.foldl (fun acc sub => acc ++ sub.enums) ([] : List EnumDef)
  let subFunctions := m.submodules.foldl (fun acc sub => acc ++ sub.functions) ([] : List FnDef)
  let subExternFns := m.submodules.foldl (fun acc sub => acc ++ sub.externFns) ([] : List ExternFnDecl)
  let subImpls := m.submodules.foldl (fun acc sub => acc ++ sub.implBlocks) ([] : List ImplBlock)
  let subTraitImpls := m.submodules.foldl (fun acc sub => acc ++ sub.traitImpls) ([] : List ImplTraitBlock)
  let subConstants := m.submodules.foldl (fun acc sub => acc ++ sub.constants) ([] : List ConstDef)
  let subTypeAliases := m.submodules.foldl (fun acc sub => acc ++ sub.typeAliases) ([] : List TypeAlias)
  { m with
    structs := m.structs ++ subStructs,
    enums := m.enums ++ subEnums,
    functions := m.functions ++ subFunctions,
    externFns := m.externFns ++ subExternFns,
    implBlocks := m.implBlocks ++ subImpls,
    traitImpls := m.traitImpls ++ subTraitImpls,
    constants := m.constants ++ subConstants,
    typeAliases := m.typeAliases ++ subTypeAliases,
    submodules := [] }

/-- Resolve Self to the concrete impl type in a Ty. -/
private def resolveSelfTy (ty : Ty) (implTy : Ty) : Ty :=
  match ty with
  | .named "Self" => implTy
  | .ref inner => .ref (resolveSelfTy inner implTy)
  | .refMut inner => .refMut (resolveSelfTy inner implTy)
  | .generic name args => .generic name (args.map fun a => resolveSelfTy a implTy)
  | .array elem n => .array (resolveSelfTy elem implTy) n
  | .heap inner => .heap (resolveSelfTy inner implTy)
  | .heapArray inner => .heapArray (resolveSelfTy inner implTy)
  | .ptrMut inner => .ptrMut (resolveSelfTy inner implTy)
  | .ptrConst inner => .ptrConst (resolveSelfTy inner implTy)
  | .fn_ params capSet retTy => .fn_ (params.map fun p => resolveSelfTy p implTy) capSet (resolveSelfTy retTy implTy)
  | other => other

mutual
private partial def resolveSelfExpr (e : Expr) (implTy : Ty) : Expr :=
  match e with
  | .structLit sp name targs fields =>
    .structLit sp name (targs.map fun t => resolveSelfTy t implTy)
      (fields.map fun (n, v) => (n, resolveSelfExpr v implTy))
  | .enumLit sp ename vname targs fields =>
    .enumLit sp ename vname (targs.map fun t => resolveSelfTy t implTy)
      (fields.map fun (n, v) => (n, resolveSelfExpr v implTy))
  | .cast sp inner targetTy => .cast sp (resolveSelfExpr inner implTy) (resolveSelfTy targetTy implTy)
  | .call sp fn targs args =>
    .call sp fn (targs.map fun t => resolveSelfTy t implTy)
      (args.map fun a => resolveSelfExpr a implTy)
  | .methodCall sp obj m targs args =>
    .methodCall sp (resolveSelfExpr obj implTy) m (targs.map fun t => resolveSelfTy t implTy)
      (args.map fun a => resolveSelfExpr a implTy)
  | .staticMethodCall sp tn m targs args =>
    .staticMethodCall sp tn m (targs.map fun t => resolveSelfTy t implTy)
      (args.map fun a => resolveSelfExpr a implTy)
  | .binOp sp op l r => .binOp sp op (resolveSelfExpr l implTy) (resolveSelfExpr r implTy)
  | .unaryOp sp op e => .unaryOp sp op (resolveSelfExpr e implTy)
  | .paren sp inner => .paren sp (resolveSelfExpr inner implTy)
  | .borrow sp inner => .borrow sp (resolveSelfExpr inner implTy)
  | .borrowMut sp inner => .borrowMut sp (resolveSelfExpr inner implTy)
  | .deref sp inner => .deref sp (resolveSelfExpr inner implTy)
  | .try_ sp inner => .try_ sp (resolveSelfExpr inner implTy)
  | .fieldAccess sp obj f => .fieldAccess sp (resolveSelfExpr obj implTy) f
  | .arrowAccess sp obj f => .arrowAccess sp (resolveSelfExpr obj implTy) f
  | .arrayLit sp elems => .arrayLit sp (elems.map fun e => resolveSelfExpr e implTy)
  | .arrayIndex sp arr idx => .arrayIndex sp (resolveSelfExpr arr implTy) (resolveSelfExpr idx implTy)
  | .allocCall sp inner alloc => .allocCall sp (resolveSelfExpr inner implTy) (resolveSelfExpr alloc implTy)
  | .match_ sp scrut arms => .match_ sp (resolveSelfExpr scrut implTy) (arms.map fun arm =>
      match arm with
      | .mk sp2 en vn bs body => .mk sp2 en vn bs (resolveSelfStmts body implTy)
      | .litArm sp2 v body => .litArm sp2 (resolveSelfExpr v implTy) (resolveSelfStmts body implTy)
      | .varArm sp2 b body => .varArm sp2 b (resolveSelfStmts body implTy))
  | .fnRef sp name => .fnRef sp name
  | .whileExpr sp cond body elseBody =>
    .whileExpr sp (resolveSelfExpr cond implTy) (resolveSelfStmts body implTy)
      (resolveSelfStmts elseBody implTy)
  | other => other

private partial def resolveSelfStmts (stmts : List Stmt) (implTy : Ty) : List Stmt :=
  stmts.map fun s => resolveSelfStmt s implTy

private partial def resolveSelfStmt (s : Stmt) (implTy : Ty) : Stmt :=
  match s with
  | .letDecl sp name isMut ty val =>
    .letDecl sp name isMut (ty.map fun t => resolveSelfTy t implTy) (resolveSelfExpr val implTy)
  | .assign sp name val => .assign sp name (resolveSelfExpr val implTy)
  | .return_ sp (some val) => .return_ sp (some (resolveSelfExpr val implTy))
  | .return_ sp none => .return_ sp none
  | .expr sp e => .expr sp (resolveSelfExpr e implTy)
  | .ifElse sp cond th el =>
    .ifElse sp (resolveSelfExpr cond implTy) (resolveSelfStmts th implTy)
      (el.map fun b => resolveSelfStmts b implTy)
  | .while_ sp cond body lbl => .while_ sp (resolveSelfExpr cond implTy) (resolveSelfStmts body implTy) lbl
  | .forLoop sp init cond step body lbl =>
    .forLoop sp (init.map fun s => resolveSelfStmt s implTy)
      (resolveSelfExpr cond implTy)
      (step.map fun s => resolveSelfStmt s implTy)
      (resolveSelfStmts body implTy) lbl
  | .fieldAssign sp obj f val =>
    .fieldAssign sp (resolveSelfExpr obj implTy) f (resolveSelfExpr val implTy)
  | .derefAssign sp target val =>
    .derefAssign sp (resolveSelfExpr target implTy) (resolveSelfExpr val implTy)
  | .arrayIndexAssign sp arr idx val =>
    .arrayIndexAssign sp (resolveSelfExpr arr implTy) (resolveSelfExpr idx implTy)
      (resolveSelfExpr val implTy)
  | .break_ sp (some e) lbl => .break_ sp (some (resolveSelfExpr e implTy)) lbl
  | .break_ sp none lbl => .break_ sp none lbl
  | .continue_ sp lbl => .continue_ sp lbl
  | .defer sp body => .defer sp (resolveSelfExpr body implTy)
  | .borrowIn sp v r reg isMut body =>
    .borrowIn sp v r reg isMut (resolveSelfStmts body implTy)
  | .arrowAssign sp obj f val =>
    .arrowAssign sp (resolveSelfExpr obj implTy) f (resolveSelfExpr val implTy)
end

/-- Resolve Self in a FnDef given the impl's type. -/
private def resolveSelfInFnDef (f : FnDef) (implTy : Ty) : FnDef :=
  { f with
    retTy := resolveSelfTy f.retTy implTy,
    params := f.params.map fun p => { p with ty := resolveSelfTy p.ty implTy },
    body := resolveSelfStmts f.body implTy }

/-- Resolve Self in all impl blocks and trait impls of a module. -/
private def resolveSelfInModule (m : Module) : Module :=
  { m with
    implBlocks := m.implBlocks.map fun ib =>
      let implTy := if ib.typeParams.isEmpty then Ty.named ib.typeName
                    else Ty.generic ib.typeName (ib.typeParams.map Ty.typeVar)
      { ib with methods := ib.methods.map fun f => resolveSelfInFnDef f implTy },
    traitImpls := m.traitImpls.map fun tb =>
      let implTy := if tb.typeParams.isEmpty then Ty.named tb.typeName
                    else Ty.generic tb.typeName (tb.typeParams.map Ty.typeVar)
      { tb with methods := tb.methods.map fun f => resolveSelfInFnDef f implTy } }

def genProgram (modules : List Module) : String :=
  -- Build qualified name → original name aliases from submodules
  let aliases : List (String × String) := modules.foldl (fun acc m =>
    acc ++ m.submodules.foldl (fun acc2 (sub : Module) =>
      acc2 ++ (sub.functions.map fun f => (sub.name ++ "_" ++ f.name, f.name))
      ++ (sub.externFns.map fun ef => (sub.name ++ "_" ++ ef.name, ef.name))
    ) ([] : List (String × String))
  ) []
  let flatModules := modules.map (resolveSelfInModule ∘ flattenModule)
  let combined : Module := {
    name := "combined",
    structs := flatModules.foldl (fun acc m => acc ++ m.structs) [],
    enums := flatModules.foldl (fun acc m => acc ++ m.enums) [],
    functions := flatModules.foldl (fun acc m => acc ++ m.functions) [],
    imports := [],
    implBlocks := flatModules.foldl (fun acc m => acc ++ m.implBlocks) [],
    traits := flatModules.foldl (fun acc m => acc ++ m.traits) [],
    traitImpls := flatModules.foldl (fun acc m => acc ++ m.traitImpls) [],
    constants := flatModules.foldl (fun acc m => acc ++ m.constants) [],
    typeAliases := flatModules.foldl (fun acc m => acc ++ m.typeAliases) [],
    externFns := flatModules.foldl (fun acc m => acc ++ m.externFns) [],
    submodules := []
  }
  -- Replace qualified call names with original function names
  let result := genModule combined
  aliases.foldl (fun (s : String) (qual, orig) =>
    s.replace ("@" ++ qual ++ "(") ("@" ++ orig ++ "(")
  ) result


end Concrete
