import Concrete.Proof.DependencyEdge

/-! # Checked-in theorem classifications (R-0004 slice 6)

GENERATED by `scripts/gen/classifications.lean`. Do not hand-edit.

The classification reads a theorem's ELABORATED TYPE, which exists only while Lean is
elaborating with the proof modules imported. The compiler imports neither and cannot:
`Examples` imports `Concrete`, so importing the proofs from `Concrete` would be a cycle. The
answer is therefore computed at generation time and checked in as data.

A STALE TABLE IS A GATE FAILURE, not a silent wrong answer: `check_dependency_edges.sh`
re-classifies from the live environment and asserts agreement. Without that, this file would be
the one place in R-0004 where evidence rests on something nobody re-derives.

A theorem ABSENT from this table classifies as `unclassified` — never as a default `contract`
or `body`. Absence means the generator has not seen it, which is exactly what `unclassified`
denotes. -/

namespace Concrete.Proof

/-- (theorem name, canonical edge kind). -/
def classificationTable : List (String × String) :=
[
  ("Concrete.Proof.parse_byte_correct", "body"),
  ("Concrete.Proof.check_length_rejects_short", "body"),
  ("Concrete.Proof.decode_header_rejects_short", "body"),
  ("Examples.CryptoVerify.Proofs.compute_tag_correct", "body"),
  ("Examples.CryptoVerify.Proofs.verify_tag_correct", "body"),
  ("Examples.CryptoVerify.Proofs.check_nonce_correct", "body"),
  ("Examples.ElfHeader.Proofs.check_magic_correct", "body"),
  ("Examples.ElfHeader.Proofs.check_class_correct", "body"),
  ("Examples.ElfHeader.Proofs.check_data_correct", "body"),
  ("Examples.ElfHeader.Proofs.check_version_correct", "body"),
  ("Examples.ElfHeader.Proofs.validate_header_correct", "body"),
  ("Examples.ConstantTimeTag.Proofs.ct_compare_different_tag_correct", "body"),
  ("Examples.ConstantTimeTag.Proofs.ct_compare_same_tag_correct", "body"),
  ("Examples.CryptoVerify.Proofs.verify_message_composed_correct", "body"),
  ("Examples.FixedCapacity.Proofs.compute_tag_zero_correct", "body"),
  ("Examples.FixedCapacity.Proofs.ring_new_correct", "body"),
  ("Examples.FixedCapacity.Proofs.ring_push_then_contains_correct", "body"),
  ("Examples.FixedCapacity.Proofs.ring_push_zero_correct", "body"),
  ("Examples.HmacSha256.Proofs.block_to_words_at_refines_spec", "contract"),
  ("Examples.HmacSha256.Proofs.block_to_words_refines_spec", "contract"),
  ("Examples.HmacSha256.Proofs.ch_refines", "body"),
  ("Examples.HmacSha256.Proofs.ch_selects_high", "body"),
  ("Examples.HmacSha256.Proofs.hmac_sha256_refines_spec", "body"),
  ("Examples.HmacSha256.Proofs.round_refines_list", "body"),
  ("Examples.HmacSha256.Proofs.sha256_compress_at_refines_spec", "body"),
  ("Examples.HmacSha256.Proofs.sha256_compress_refines_spec", "body"),
  ("Examples.HmacSha256.Proofs.sha256_hash_refines_spec", "body"),
  ("Examples.HmacSha256.Proofs.sha256_init_correct", "body"),
  ("Examples.HmacSha256.Proofs.sha256_schedule_refines_spec", "body"),
  ("Examples.HmacSha256.Proofs.state_to_bytes_refines_spec", "body"),
  ("Examples.LoopInvariant.Proofs.count_up_loop_preserves", "contract"),
  ("Examples.ParseValidate.Proofs.parse_header_too_short", "body"),
  ("Examples.ParseValidate.Proofs.validate_header_fields_success", "body"),
  ("Examples.ParseValidate.Proofs.validate_version_correct", "body"),
  ("Examples.ProofPatterns.Proofs.add_three_correct", "body"),
  ("Examples.ProofPatterns.Proofs.combine_correct", "body"),
  ("Examples.ProofPatterns.Proofs.copy2_copies_faithfully", "body"),
  ("Examples.ProofPatterns.Proofs.dbl_correct", "body"),
  ("Examples.ProofPatterns.Proofs.ghost_sum_correct", "body"),
  ("Examples.ProofPatterns.Proofs.inc_correct", "body"),
  ("Examples.ProofPatterns.Proofs.put_writes_index_1_frames_rest", "body"),
  ("Examples.ProofPatterns.Proofs.scale_by_two_correct", "body"),
  ("Examples.ProofPatterns.Proofs.sum4_totals_concrete", "body")
]

/-- The edge a theorem implies, or `unclassified` when the table has not seen it. -/
def classifiedEdgeOf (thm : String) : DependencyEdge :=
  match (classificationTable.find? (fun r => r.1 == thm)).map (·.2) with
  | some "contract" => .contract
  | some "body"     => .body
  | some "trusted"  => .trusted
  | some "missing"  => .missing
  -- An unrecognised tag is `unclassified`, not a guess. A tag this function does not know is a
  -- generator/consumer mismatch, and defaulting to anything current would convert that mismatch
  -- into a claim.
  | _               => .unclassified

end Concrete.Proof
