#!/usr/bin/env bash
# THE PUBLISHED ARTIFACT, REGENERATED AND COMPARED — NOT EYEBALLED.
#
# The campaign summary is the record everything downstream reads. A fixture someone once copied and
# has since hand-edited is worth nothing: this session already produced one, and the schema decoder
# caught it as `missing_key(families_digest)` because a field had been added and the "baseline" had
# not moved. That is the failure mode this gate exists to make impossible.
#
# So the baseline is not a file anyone writes. It is the output of the production publisher, put
# through one documented normaliser, committed as exact bytes. This gate runs the same producer, the
# same normaliser, and requires byte-for-byte equality — and separately requires the published key
# set to equal the declared schema, so a field added to the writer without being declared fails here
# rather than being decoded as an unknown key at publication time.
#
#   THE PRODUCER IS SELECTED BY IDENTITY, NEVER BY ORDINAL. `FAMILY=85` names a SLOT: inserting a
#   family renumbers everything after it, so a baseline regenerated by ordinal silently starts
#   describing a different experiment. FAMILY_ID names the family and FAMILY_SPEC pins the digest of
#   the mutation it must still be, so a family that keeps its name while becoming something else
#   fails here instead of quietly redefining the baseline.
#
#   REGENERATE WITH:
#       (nothing to remove: evidence is keyed by run id and cannot collide)
#       FAMILY_ID=mint-missing-result-refusal \
#       FAMILY_SPEC=bd4fae0e3629767ff4a4cd2a71c753e3555f8eb389c10ef089e36833cc0030a6 \
#         bash scripts/tests/check_gate_mutation_coverage.sh
#       bash scripts/tests/lib/normalize_campaign_summary.sh .mutation-campaign-summary.partial \
#           > scripts/tests/fixtures/campaign-summary.golden
#
#   NEVER hand-edit the golden file. If it disagrees with production, the producer is the authority:
#   either the change is intended and the baseline is regenerated by that command in the same commit,
#   or the change is a defect and the producer is what needs fixing.
#
# COST: this runs a real single-family campaign, several minutes. It is a separate gate for that
# reason — the common path should not pay for it, and a golden that is only checked when someone
# remembers is not a golden.
set -uEo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
GOLDEN="$ROOT_DIR/scripts/tests/fixtures/campaign-summary.golden"
NORMALIZE="$ROOT_DIR/scripts/tests/lib/normalize_campaign_summary.sh"
. "$ROOT_DIR/scripts/tests/lib/campaign_supervise.sh" || { echo "cannot load the decision library" >&2; exit 2; }

PASS=0; FAIL=0
ok(){ echo "  ok   $1"; PASS=$((PASS+1)); }
no(){ echo "  FAIL $1"; FAIL=$((FAIL+1)); }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

[ -s "$GOLDEN" ] || { echo "error: golden baseline missing at $GOLDEN — regenerate it (see header)" >&2; exit 2; }

echo "=== the baseline is a NORMALISED PROJECTION, and is checked as one ==="
# A NORMALISED RECORD IS NOT A PUBLISHED RECORD. Decoding the baseline under the published schema
# fails by construction: the volatile values are replaced by <VOLATILE>, which is not the canonical
# number the schema requires for secs_*. Measured, and it is the decoder being right — I asserted
# the opposite in a commit message on the strength of a diagnostic that had errored instead of
# printing its result.
#
# So the RAW artifact is what must decode, below, after the producer runs; what is checked here is
# the property normalisation actually preserves — the key set — plus that every declared volatile
# key really was masked, so a masked field cannot quietly become an unmasked one.
# THE LIST COMES FROM THE NORMALISER, not a second copy here. Two lists that agree today are two
# lists that can disagree tomorrow, and the one that would silently win is whichever the comparison
# happens to consult.
_VOL="$(sed -n 's/^VOLATILE_KEYS="\(.*\)"$/\1/p' "$NORMALIZE")"
[ -n "$_VOL" ] || { echo "error: could not read VOLATILE_KEYS from $NORMALIZE" >&2; exit 2; }
_vol_missing=""
for _k in $_VOL; do
  grep -qxF "$_k=<VOLATILE>" "$GOLDEN" || _vol_missing="$_vol_missing $_k"
done
[ -z "$_vol_missing" ] && ok "every declared volatile key is masked in the baseline" \
                       || no "unmasked volatile keys in the baseline:$_vol_missing"
# ...and nothing ELSE is masked, or the baseline would be comparing less than it appears to.
_vol_declared="$(printf '%s\n' $_VOL | grep -c .)"
_vol_extra="$(grep -c '=<VOLATILE>' "$GOLDEN")"
[ "$_vol_extra" = "$_vol_declared" ] \
  && ok "exactly the $_vol_declared declared volatile keys are masked, nothing more" \
  || no "$_vol_extra masked values, expected exactly $_vol_declared — a masked field that is not declared hides a real difference"

echo "=== its key set equals the declared schema exactly ==="
printf '%s\n' $CAMPAIGN_SCHEMA_PUBLISHED | LC_ALL=C sort > "$TMP/declared"
sed -n 's/^\([a-z_]*\)=.*/\1/p' "$GOLDEN" | LC_ALL=C sort > "$TMP/published"
_missing="$(comm -23 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
_extra="$(comm -13 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
{ [ -z "$_missing" ] && [ -z "$_extra" ]; } \
  && ok "published keys = declared schema ($(awk 'END{print NR}' "$TMP/declared") keys)" \
  || no "schema disagreement — declared-but-absent: ${_missing:-none}  published-but-undeclared: ${_extra:-none}"

echo "=== regenerating from the production publisher ==="
# THE GATE DOES NOT DESTROY EVIDENCE IT DID NOT CREATE. This was an unconditional
# `rm -rf .mutation-evidence`, which deletes every retained transcript from every prior run — the
# durable per-family evidence the rest of this harness exists to produce. A gate that clears the
# workspace by deleting the archive is trading the thing being protected for a convenience.
# Records are already keyed by run id and cannot collide, so nothing needs removing.
:
GOLDEN_FAMILY_ID="mint-missing-result-refusal"
GOLDEN_FAMILY_SPEC="bd4fae0e3629767ff4a4cd2a71c753e3555f8eb389c10ef089e36833cc0030a6"
PRODUCER_OK=1
# THE ARTIFACT MUST BE NEWER THAN THE INVOCATION THAT CLAIMS TO HAVE WRITTEN IT.
#
# `.mutation-campaign-summary.partial` is a shared path and the producer releases the repository lock
# when it exits, so the file read afterwards is not necessarily the file this run produced. A stale
# artifact left by an earlier run is exactly what was compared once already, and the run id that
# would have distinguished them is normalised away before the byte comparison. Recording the moment
# the producer starts makes "this artifact predates the run that supposedly wrote it" detectable.
_PROD_START="$(date +%s)"
# AND THE RUN IS IDENTIFIED, NOT MERELY TIMED. A second-resolution mtime cannot distinguish this
# run's artifact from a replacement written in the same second. Every campaign creates exactly one
# evidence directory named for its run id, so the set of directories before and after names THIS
# invocation — and the artifact must carry that id. That is identity, not chronology.
_EV_BEFORE="$TMP/ev.before"; _EV_AFTER="$TMP/ev.after"
( cd "$ROOT_DIR/.mutation-evidence" 2>/dev/null && ls -1 ) 2>/dev/null | LC_ALL=C sort > "$_EV_BEFORE" || : > "$_EV_BEFORE"
if FAMILY_ID="$GOLDEN_FAMILY_ID" FAMILY_SPEC="$GOLDEN_FAMILY_SPEC" \
     bash "$ROOT_DIR/scripts/tests/check_gate_mutation_coverage.sh" > "$TMP/producer.log" 2>&1; then
  ok "the producer ran and published"
else
  no "the producer failed (exit $?) — see the tail below"
  PRODUCER_OK=0
  tail -5 "$TMP/producer.log" | sed 's/^/       /'
fi

# THE ARTIFACT IS SNAPSHOTTED THE MOMENT THE PRODUCER RETURNS.
#
# The inner campaign releases the repository lock when it exits, so between production and the two
# reads below there is a window in which another partial run could replace the shared artifact — and
# this gate would then decode one file and compare another. Everything downstream reads the copy.
# A FAILED PRODUCER LEAVES THE PREVIOUS RUN'S ARTIFACT IN PLACE, AND IT MUST NOT BE COMPARED.
#
# MEASURED: a run whose producer could not take the repository lock wrote nothing, and this gate then
# decoded and byte-compared the artifact from forty minutes earlier — reporting "decodes under the
# published schema" and "byte-identical to the committed baseline" as ok lines. Two green assertions
# about a run that never happened, next to the red one saying so. Everything downstream is refused
# when the producer did not publish; an absent result is not a passing one.
RAW="$TMP/raw.partial"
# THE IDENTITY CHECK RUNS ON EVERY PATH, so the control population is the same whether the producer
# succeeded or not. A control that only exists on the happy path makes the pinned count disagree with
# reality exactly when something has gone wrong — which is when the count matters most.
( cd "$ROOT_DIR/.mutation-evidence" 2>/dev/null && ls -1 ) 2>/dev/null | LC_ALL=C sort > "$_EV_AFTER" || : > "$_EV_AFTER"
_new_runs="$(comm -13 "$_EV_BEFORE" "$_EV_AFTER")"
_new_count="$(printf '%s\n' "$_new_runs" | grep -c . || true)"
_art_run="$(sed -n 's/^run_id=//p' "$ROOT_DIR/.mutation-campaign-summary.partial" 2>/dev/null | head -1)"
if [ "$_new_count" = "1" ] && [ "$_art_run" = "$_new_runs" ]; then
  ok "the artifact carries the run id of the evidence directory this invocation created"
else
  no "the artifact is not identifiable as this invocation's (created $_new_count evidence dirs; artifact names '${_art_run:-<none>}', this run created '${_new_runs:-<none>}')"
  PRODUCER_OK=0
fi

if [ "$PRODUCER_OK" != "1" ]; then
  : > "$RAW"
elif [ -s "$ROOT_DIR/.mutation-campaign-summary.partial" ]; then
  cp "$ROOT_DIR/.mutation-campaign-summary.partial" "$RAW" || : > "$RAW"
else
  : > "$RAW"
fi

echo "=== the RAW artifact decodes as a published record, before normalisation ==="
# VALIDATED BEFORE NORMALISATION. Normalising first would mask the very fields a malformed publisher
# would corrupt, so the raw bytes are what get decoded.
if [ "$PRODUCER_OK" != "1" ]; then
  no "the producer did not publish, so there is nothing this run produced to decode"
elif [ -s "$RAW" ]; then
  _rawdec="$(decode_candidate "$RAW" "$CAMPAIGN_SCHEMA_PUBLISHED")"
  [ -z "$_rawdec" ] && ok "the freshly published artifact decodes under the published schema" \
                    || no "the freshly published artifact does not decode: $_rawdec"
else
  no "no artifact to decode"
fi

echo "=== the regenerated artifact matches the baseline byte for byte ==="
if [ "$PRODUCER_OK" != "1" ]; then
  no "the producer did not publish, so no comparison against the baseline is possible"
elif [ -s "$RAW" ]; then
  # THE NORMALISER'S STATUS IS CHECKED. Ignoring it meant a failed subprocess that had already
  # written plausible bytes would be compared as if it had succeeded — the same "no output means
  # success" inference this harness refuses everywhere else.
  if ! bash "$NORMALIZE" "$RAW" > "$TMP/fresh"; then
    no "the normaliser failed; its output cannot be compared"
    printf '%s\n' "" > "$TMP/fresh"
  fi
  if cmp -s "$TMP/fresh" "$GOLDEN"; then
    ok "regenerated output is byte-identical to the committed baseline"
  else
    no "the baseline is stale or the producer changed — first differences:"
    diff "$GOLDEN" "$TMP/fresh" | head -8 | sed 's/^/       /'
    echo "       regenerate deliberately with the command in this file's header" >&2
  fi
else
  no "the producer left no artifact to compare"
fi

echo ""
# THE POPULATION IS PINNED, NOT JUST THE FAILURE COUNT.
#
# Exiting on FAIL==0 alone means DELETING a control is indistinguishable from passing it: the gate
# reports fewer assertions and still exits green. This harness has already been bitten by exactly
# that — 240 probes were silently lost from another gate the same way — and this round's review
# found controls here that had been inert for rounds without anyone noticing. Changing the count is
# a deliberate act, recorded in the same commit as the control that changed it.
EXPECTED_CONTROLS=7
_total=$((PASS + FAIL))
if [ "$_total" -ne "$EXPECTED_CONTROLS" ]; then
  echo "  FAIL this gate ran $_total controls, expected $EXPECTED_CONTROLS — one was added or removed"
  echo "       without updating EXPECTED_CONTROLS in the same commit."
  FAIL=$((FAIL + 1))
fi

echo "CAMPAIGN-SUMMARY-GOLDEN: PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
