#!/usr/bin/env bash
# THE PUBLISHED ARTIFACT, REGENERATED AND COMPARED — NOT EYEBALLED.
#
# The campaign summary is the record everything downstream reads. A fixture someone once copied and
# has since hand-edited is worth nothing: this session already produced one, and the schema decoder
# caught it as `missing_key(families_digest)` because a field had been added and the "baseline" had
# not moved. That is the failure mode this gate exists to make impossible.
#
# So the baseline is not a file anyone writes. It is the output of the production publisher, put
# through one documented normaliser, committed as exact bytes. This gate runs the same producer, the
# same normaliser, and requires byte-for-byte equality — and separately requires the published key
# set to equal the declared schema, so a field added to the writer without being declared fails here
# rather than being decoded as an unknown key at publication time.
#
#   THE PRODUCER IS SELECTED BY IDENTITY, NEVER BY ORDINAL. `FAMILY=85` names a SLOT: inserting a
#   family renumbers everything after it, so a baseline regenerated by ordinal silently starts
#   describing a different experiment. FAMILY_ID names the family and FAMILY_SPEC pins the digest of
#   the mutation it must still be, so a family that keeps its name while becoming something else
#   fails here instead of quietly redefining the baseline.
#
#   REGENERATE WITH:
#       rm -rf .mutation-evidence
#       FAMILY_ID=mint-missing-result-refusal \
#       FAMILY_SPEC=e13065919c92a291aa6feebce1e65326969017d6b8ac69dafce4146516b1d16b \
#         bash scripts/tests/check_gate_mutation_coverage.sh
#       bash scripts/tests/lib/normalize_campaign_summary.sh .mutation-campaign-summary.partial \
#           > scripts/tests/fixtures/campaign-summary.golden
#
#   NEVER hand-edit the golden file. If it disagrees with production, the producer is the authority:
#   either the change is intended and the baseline is regenerated by that command in the same commit,
#   or the change is a defect and the producer is what needs fixing.
#
# COST: this runs a real single-family campaign, several minutes. It is a separate gate for that
# reason — the common path should not pay for it, and a golden that is only checked when someone
# remembers is not a golden.
set -uEo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
GOLDEN="$ROOT_DIR/scripts/tests/fixtures/campaign-summary.golden"
NORMALIZE="$ROOT_DIR/scripts/tests/lib/normalize_campaign_summary.sh"
. "$ROOT_DIR/scripts/tests/lib/campaign_supervise.sh" || { echo "cannot load the decision library" >&2; exit 2; }

PASS=0; FAIL=0
ok(){ echo "  ok   $1"; PASS=$((PASS+1)); }
no(){ echo "  FAIL $1"; FAIL=$((FAIL+1)); }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

[ -s "$GOLDEN" ] || { echo "error: golden baseline missing at $GOLDEN — regenerate it (see header)" >&2; exit 2; }

echo "=== the baseline is a NORMALISED PROJECTION, and is checked as one ==="
# A NORMALISED RECORD IS NOT A PUBLISHED RECORD. Decoding the baseline under the published schema
# fails by construction: the volatile values are replaced by <VOLATILE>, which is not the canonical
# number the schema requires for secs_*. Measured, and it is the decoder being right — I asserted
# the opposite in a commit message on the strength of a diagnostic that had errored instead of
# printing its result.
#
# So the RAW artifact is what must decode, below, after the producer runs; what is checked here is
# the property normalisation actually preserves — the key set — plus that every declared volatile
# key really was masked, so a masked field cannot quietly become an unmasked one.
_vol_missing=""
for _k in secs_total secs_copy secs_build secs_gate secs_other run_id evidence_dir evidence_root; do
  grep -qxF "$_k=<VOLATILE>" "$GOLDEN" || _vol_missing="$_vol_missing $_k"
done
[ -z "$_vol_missing" ] && ok "every declared volatile key is masked in the baseline" \
                       || no "unmasked volatile keys in the baseline:$_vol_missing"
# ...and nothing ELSE is masked, or the baseline would be comparing less than it appears to.
_vol_extra="$(grep -c '=<VOLATILE>' "$GOLDEN")"
[ "$_vol_extra" = "8" ] && ok "exactly the 8 declared volatile keys are masked, nothing more" \
                        || no "$_vol_extra masked values, expected exactly 8"

echo "=== its key set equals the declared schema exactly ==="
printf '%s\n' $CAMPAIGN_SCHEMA_PUBLISHED | LC_ALL=C sort > "$TMP/declared"
sed -n 's/^\([a-z_]*\)=.*/\1/p' "$GOLDEN" | LC_ALL=C sort > "$TMP/published"
_missing="$(comm -23 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
_extra="$(comm -13 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
{ [ -z "$_missing" ] && [ -z "$_extra" ]; } \
  && ok "published keys = declared schema ($(awk 'END{print NR}' "$TMP/declared") keys)" \
  || no "schema disagreement — declared-but-absent: ${_missing:-none}  published-but-undeclared: ${_extra:-none}"

echo "=== regenerating from the production publisher ==="
rm -rf "$ROOT_DIR/.mutation-evidence"
GOLDEN_FAMILY_ID="mint-missing-result-refusal"
GOLDEN_FAMILY_SPEC="e13065919c92a291aa6feebce1e65326969017d6b8ac69dafce4146516b1d16b"
if FAMILY_ID="$GOLDEN_FAMILY_ID" FAMILY_SPEC="$GOLDEN_FAMILY_SPEC" \
     bash "$ROOT_DIR/scripts/tests/check_gate_mutation_coverage.sh" > "$TMP/producer.log" 2>&1; then
  ok "the producer ran and published"
else
  no "the producer failed (exit $?) — see the tail below"
  tail -5 "$TMP/producer.log" | sed 's/^/       /'
fi

echo "=== the RAW artifact decodes as a published record, before normalisation ==="
# VALIDATED BEFORE NORMALISATION. Normalising first would mask the very fields a malformed publisher
# would corrupt, so the raw bytes are what get decoded.
if [ -s "$ROOT_DIR/.mutation-campaign-summary.partial" ]; then
  _rawdec="$(decode_candidate "$ROOT_DIR/.mutation-campaign-summary.partial" "$CAMPAIGN_SCHEMA_PUBLISHED")"
  [ -z "$_rawdec" ] && ok "the freshly published artifact decodes under the published schema" \
                    || no "the freshly published artifact does not decode: $_rawdec"
else
  no "no artifact to decode"
fi

echo "=== the regenerated artifact matches the baseline byte for byte ==="
if [ -s "$ROOT_DIR/.mutation-campaign-summary.partial" ]; then
  bash "$NORMALIZE" "$ROOT_DIR/.mutation-campaign-summary.partial" > "$TMP/fresh"
  if cmp -s "$TMP/fresh" "$GOLDEN"; then
    ok "regenerated output is byte-identical to the committed baseline"
  else
    no "the baseline is stale or the producer changed — first differences:"
    diff "$GOLDEN" "$TMP/fresh" | head -8 | sed 's/^/       /'
    echo "       regenerate deliberately with the command in this file's header" >&2
  fi
else
  no "the producer left no artifact to compare"
fi

echo ""
echo "CAMPAIGN-SUMMARY-GOLDEN: PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
