#!/usr/bin/env bash
# THE PUBLISHED ARTIFACT, REGENERATED AND COMPARED — NOT EYEBALLED.
#
# The campaign summary is the record everything downstream reads. A fixture someone once copied and
# has since hand-edited is worth nothing: this session already produced one, and the schema decoder
# caught it as `missing_key(families_digest)` because a field had been added and the "baseline" had
# not moved. That is the failure mode this gate exists to make impossible.
#
# So the baseline is not a file anyone writes. It is the output of the production publisher, put
# through one documented normaliser, committed as exact bytes. This gate runs the same producer, the
# same normaliser, and requires byte-for-byte equality — and separately requires the published key
# set to equal the declared schema, so a field added to the writer without being declared fails here
# rather than being decoded as an unknown key at publication time.
#
#   REGENERATE WITH:
#       rm -rf .mutation-evidence
#       FAMILY=85 bash scripts/tests/check_gate_mutation_coverage.sh
#       bash scripts/tests/lib/normalize_campaign_summary.sh .mutation-campaign-summary.partial \
#           > scripts/tests/fixtures/campaign-summary.golden
#
#   NEVER hand-edit the golden file. If it disagrees with production, the producer is the authority:
#   either the change is intended and the baseline is regenerated by that command in the same commit,
#   or the change is a defect and the producer is what needs fixing.
#
# COST: this runs a real single-family campaign, several minutes. It is a separate gate for that
# reason — the common path should not pay for it, and a golden that is only checked when someone
# remembers is not a golden.
set -uEo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
GOLDEN="$ROOT_DIR/scripts/tests/fixtures/campaign-summary.golden"
NORMALIZE="$ROOT_DIR/scripts/tests/lib/normalize_campaign_summary.sh"
. "$ROOT_DIR/scripts/tests/lib/campaign_supervise.sh" || { echo "cannot load the decision library" >&2; exit 2; }

PASS=0; FAIL=0
ok(){ echo "  ok   $1"; PASS=$((PASS+1)); }
no(){ echo "  FAIL $1"; FAIL=$((FAIL+1)); }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

[ -s "$GOLDEN" ] || { echo "error: golden baseline missing at $GOLDEN — regenerate it (see header)" >&2; exit 2; }

echo "=== the golden baseline is itself a valid published record ==="
# A baseline that does not decode is not a baseline; it would freeze whatever malformation it holds.
_dec="$(decode_candidate "$GOLDEN" "$CAMPAIGN_SCHEMA_PUBLISHED")"
[ -z "$_dec" ] && ok "the committed baseline decodes under the published schema" \
                || no "the committed baseline does not decode: $_dec"

echo "=== its key set equals the declared schema exactly ==="
printf '%s\n' $CAMPAIGN_SCHEMA_PUBLISHED | LC_ALL=C sort > "$TMP/declared"
sed -n 's/^\([a-z_]*\)=.*/\1/p' "$GOLDEN" | LC_ALL=C sort > "$TMP/published"
_missing="$(comm -23 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
_extra="$(comm -13 "$TMP/declared" "$TMP/published" | tr '\n' ',')"
{ [ -z "$_missing" ] && [ -z "$_extra" ]; } \
  && ok "published keys = declared schema ($(awk 'END{print NR}' "$TMP/declared") keys)" \
  || no "schema disagreement — declared-but-absent: ${_missing:-none}  published-but-undeclared: ${_extra:-none}"

echo "=== regenerating from the production publisher ==="
rm -rf "$ROOT_DIR/.mutation-evidence"
if FAMILY=85 bash "$ROOT_DIR/scripts/tests/check_gate_mutation_coverage.sh" > "$TMP/producer.log" 2>&1; then
  ok "the producer ran and published"
else
  no "the producer failed (exit $?) — see the tail below"
  tail -5 "$TMP/producer.log" | sed 's/^/       /'
fi

echo "=== the regenerated artifact matches the baseline byte for byte ==="
if [ -s "$ROOT_DIR/.mutation-campaign-summary.partial" ]; then
  bash "$NORMALIZE" "$ROOT_DIR/.mutation-campaign-summary.partial" > "$TMP/fresh"
  if cmp -s "$TMP/fresh" "$GOLDEN"; then
    ok "regenerated output is byte-identical to the committed baseline"
  else
    no "the baseline is stale or the producer changed — first differences:"
    diff "$GOLDEN" "$TMP/fresh" | head -8 | sed 's/^/       /'
    echo "       regenerate deliberately with the command in this file's header" >&2
  fi
else
  no "the producer left no artifact to compare"
fi

echo ""
echo "CAMPAIGN-SUMMARY-GOLDEN: PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
